// Generated by pnpm charts:generate-landing-catalog.
// Source: @tanstack/react-charts-catalog catalogCases.

import { lazy, Suspense, useEffect, useRef } from 'react'
import type { ComponentType, ReactNode } from 'react'
import { ClientOnly } from '@tanstack/react-router'
import { Hydrate } from '@tanstack/react-start'
import { visible } from '@tanstack/react-start/hydration'
import type {
  CatalogCaseId,
  CatalogChartProps,
} from '@tanstack/react-charts-catalog'
import CatalogChartCase0 from '@tanstack/react-charts-catalog/cases/03-temperature-range-band'
import CatalogChartCase1 from '@tanstack/react-charts-catalog/cases/bar-grouped'
import CatalogChartCase2 from '@tanstack/react-charts-catalog/cases/bar-vertical-sorted'
import CatalogChartCase3 from '@tanstack/react-charts-catalog/cases/bar-stacked'

const CatalogChartCase4 = lazy<ComponentType<CatalogChartProps>>(
  () => import('@tanstack/react-charts-catalog/cases/scatter-bubble'),
)
const CatalogChartCase5 = lazy<ComponentType<CatalogChartProps>>(
  () => import('@tanstack/react-charts-catalog/cases/14-error-bars'),
)
const CatalogChartCase6 = lazy<ComponentType<CatalogChartProps>>(
  () => import('@tanstack/react-charts-catalog/cases/01-line-gaps'),
)
const CatalogChartCase7 = lazy<ComponentType<CatalogChartProps>>(
  () => import('@tanstack/react-charts-catalog/cases/04-stacked-time-area'),
)

export const chartsLandingCaseIds = [
  '03-temperature-range-band',
  'bar-grouped',
  'bar-vertical-sorted',
  'bar-stacked',
  'scatter-bubble',
  '14-error-bars',
  '01-line-gaps',
  '04-stacked-time-area',
] as const satisfies readonly CatalogCaseId[]

export type ChartsLandingCaseId = (typeof chartsLandingCaseIds)[number]

export const chartsLandingInitialCaseIds = [
  '03-temperature-range-band',
  'bar-grouped',
  'bar-vertical-sorted',
  'bar-stacked',
] as const satisfies readonly ChartsLandingCaseId[]

const hydrateWhen = visible({ rootMargin: '480px 144px' })

export function ChartsLandingCatalogChart({
  aspectRatio,
  caseId,
  height,
  idPrefix,
  initialWidth,
  interactive = true,
  onHydrated,
  preview = false,
  revision = 0,
}: {
  aspectRatio?: number
  caseId: ChartsLandingCaseId
  height?: number
  idPrefix: string
  initialWidth: number
  interactive?: boolean
  onHydrated?: () => void
  preview?: boolean
  revision?: number
}) {
  const chartProps = {
    aspectRatio,
    height,
    idPrefix,
    initialWidth,
    interactive,
    preview,
    revision,
  } satisfies CatalogChartProps
  let chart: ReactNode

  switch (caseId) {
    case '03-temperature-range-band':
      chart = (
        <Hydrate when={hydrateWhen} split onHydrated={onHydrated}>
          <CatalogChartCase0 {...chartProps} />
        </Hydrate>
      )
      break
    case 'bar-grouped':
      chart = (
        <Hydrate when={hydrateWhen} split onHydrated={onHydrated}>
          <CatalogChartCase1 {...chartProps} />
        </Hydrate>
      )
      break
    case 'bar-vertical-sorted':
      chart = (
        <Hydrate when={hydrateWhen} split onHydrated={onHydrated}>
          <CatalogChartCase2 {...chartProps} />
        </Hydrate>
      )
      break
    case 'bar-stacked':
      chart = (
        <Hydrate when={hydrateWhen} split onHydrated={onHydrated}>
          <CatalogChartCase3 {...chartProps} />
        </Hydrate>
      )
      break
    case 'scatter-bubble':
      chart = (
        <ClientOnly>
          <Suspense fallback={null}>
            <ChartMounted onMount={onHydrated}>
              <CatalogChartCase4 {...chartProps} />
            </ChartMounted>
          </Suspense>
        </ClientOnly>
      )
      break
    case '14-error-bars':
      chart = (
        <ClientOnly>
          <Suspense fallback={null}>
            <ChartMounted onMount={onHydrated}>
              <CatalogChartCase5 {...chartProps} />
            </ChartMounted>
          </Suspense>
        </ClientOnly>
      )
      break
    case '01-line-gaps':
      chart = (
        <ClientOnly>
          <Suspense fallback={null}>
            <ChartMounted onMount={onHydrated}>
              <CatalogChartCase6 {...chartProps} />
            </ChartMounted>
          </Suspense>
        </ClientOnly>
      )
      break
    case '04-stacked-time-area':
      chart = (
        <ClientOnly>
          <Suspense fallback={null}>
            <ChartMounted onMount={onHydrated}>
              <CatalogChartCase7 {...chartProps} />
            </ChartMounted>
          </Suspense>
        </ClientOnly>
      )
      break
  }

  return (
    <div
      className="charts-catalog-chart relative h-full w-full overflow-visible"
      data-chart-case={caseId}
      style={{ height }}
    >
      {chart}
    </div>
  )
}

function ChartMounted({
  children,
  onMount,
}: {
  children: ReactNode
  onMount?: () => void
}) {
  const didNotify = useRef(false)

  useEffect(() => {
    if (didNotify.current) return
    didNotify.current = true
    onMount?.()
  }, [onMount])

  return children
}
