// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SponsorsEmbedImport } from './routes/sponsors-embed'
import { Route as BlogImport } from './routes/blog'
import { Route as IndexImport } from './routes/index'
import { Route as BlogIndexImport } from './routes/blog.index'
import { Route as BlogSplatImport } from './routes/blog.$'
import { Route as QueryVersionIndexImport } from './routes/query.$version.index'

// Create/Update Routes

const SponsorsEmbedRoute = SponsorsEmbedImport.update({
  path: '/sponsors-embed',
  getParentRoute: () => rootRoute,
} as any)

const BlogRoute = BlogImport.update({
  path: '/blog',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BlogIndexRoute = BlogIndexImport.update({
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)

const BlogSplatRoute = BlogSplatImport.update({
  path: '/$',
  getParentRoute: () => BlogRoute,
} as any)

const QueryVersionIndexRoute = QueryVersionIndexImport.update({
  path: '/query/$version/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/blog': {
      preLoaderRoute: typeof BlogImport
      parentRoute: typeof rootRoute
    }
    '/sponsors-embed': {
      preLoaderRoute: typeof SponsorsEmbedImport
      parentRoute: typeof rootRoute
    }
    '/blog/$': {
      preLoaderRoute: typeof BlogSplatImport
      parentRoute: typeof BlogImport
    }
    '/blog/': {
      preLoaderRoute: typeof BlogIndexImport
      parentRoute: typeof BlogImport
    }
    '/query/$version/': {
      preLoaderRoute: typeof QueryVersionIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  BlogRoute.addChildren([BlogSplatRoute, BlogIndexRoute]),
  SponsorsEmbedRoute,
  QueryVersionIndexRoute,
])
