import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

import { catalogCases } from '@tanstack/react-charts-catalog'

type CatalogCaseMetadata = {
  id: string
  order: number
}

const landingHeroCaseIds = [
  '03-temperature-range-band',
  'bar-grouped',
  'bar-vertical-sorted',
  'bar-stacked',
  'scatter-bubble',
  '14-error-bars',
  '01-line-gaps',
  '04-stacked-time-area',
] as const

const landingInitialHeroCaseIds = [
  '03-temperature-range-band',
  'bar-grouped',
  'bar-vertical-sorted',
  'bar-stacked',
] as const

const scriptDirectory = dirname(fileURLToPath(import.meta.url))
const repositoryRoot = resolve(scriptDirectory, '..')
const outputFile = resolve(
  repositoryRoot,
  'src/components/charts/ChartsLandingCatalogChart.tsx',
)

export function createChartsLandingCatalogSource(
  metadata: ReadonlyArray<CatalogCaseMetadata>,
) {
  const orderedCases = [...metadata].sort(
    (left, right) =>
      left.order - right.order || left.id.localeCompare(right.id),
  )
  const caseIds = new Set<string>()

  for (const catalogCase of orderedCases) {
    if (!catalogCase.id || !Number.isInteger(catalogCase.order)) {
      throw new Error('Every catalog case requires an id and integer order.')
    }
    if (caseIds.has(catalogCase.id)) {
      throw new Error(`Duplicate catalog case id: ${catalogCase.id}`)
    }
    caseIds.add(catalogCase.id)
  }

  const landingCases = landingHeroCaseIds.map((caseId) => {
    const catalogCase = orderedCases.find(
      (candidate) => candidate.id === caseId,
    )
    if (!catalogCase) throw new Error(`Missing landing hero case: ${caseId}`)
    return catalogCase
  })
  const initialCaseIds = new Set<string>(landingInitialHeroCaseIds)
  const staticImports = landingCases.flatMap((catalogCase, index) =>
    initialCaseIds.has(catalogCase.id)
      ? [
          `import CatalogChartCase${index} from '@tanstack/react-charts-catalog/cases/${catalogCase.id}'`,
        ]
      : [],
  )
  const lazyComponents = landingCases.flatMap((catalogCase, index) =>
    initialCaseIds.has(catalogCase.id)
      ? []
      : [
          `const CatalogChartCase${index} = lazy<ComponentType<CatalogChartProps>>(`,
          `  () => import('@tanstack/react-charts-catalog/cases/${catalogCase.id}'),`,
          ')',
        ],
  )
  const ids = landingCases.map((catalogCase) => `  '${catalogCase.id}',`)
  const initialIds = landingInitialHeroCaseIds.map((caseId) => `  '${caseId}',`)
  const cases = landingCases.flatMap((catalogCase, index) => {
    const header = [`    case '${catalogCase.id}':`, '      chart = (']
    const footer = ['      )', '      break']

    if (initialCaseIds.has(catalogCase.id)) {
      return [
        ...header,
        '        <Hydrate when={hydrateWhen} split onHydrated={onHydrated}>',
        `          <CatalogChartCase${index} {...chartProps} />`,
        '        </Hydrate>',
        ...footer,
      ]
    }

    return [
      ...header,
      '        <ClientOnly>',
      '          <Suspense fallback={null}>',
      '            <ChartMounted onMount={onHydrated}>',
      `              <CatalogChartCase${index} {...chartProps} />`,
      '            </ChartMounted>',
      '          </Suspense>',
      '        </ClientOnly>',
      ...footer,
    ]
  })

  return [
    '// Generated by pnpm charts:generate-landing-catalog.',
    '// Source: @tanstack/react-charts-catalog catalogCases.',
    '',
    "import { lazy, Suspense, useEffect, useRef } from 'react'",
    "import type { ComponentType, ReactNode } from 'react'",
    "import { ClientOnly } from '@tanstack/react-router'",
    "import { Hydrate } from '@tanstack/react-start'",
    "import { visible } from '@tanstack/react-start/hydration'",
    'import type {',
    '  CatalogCaseId,',
    '  CatalogChartProps,',
    "} from '@tanstack/react-charts-catalog'",
    ...staticImports,
    '',
    ...lazyComponents,
    '',
    'export const chartsLandingCaseIds = [',
    ...ids,
    '] as const satisfies readonly CatalogCaseId[]',
    '',
    'export type ChartsLandingCaseId = (typeof chartsLandingCaseIds)[number]',
    '',
    'export const chartsLandingInitialCaseIds = [',
    ...initialIds,
    '] as const satisfies readonly ChartsLandingCaseId[]',
    '',
    "const hydrateWhen = visible({ rootMargin: '480px 144px' })",
    '',
    'export function ChartsLandingCatalogChart({',
    '  aspectRatio,',
    '  caseId,',
    '  height,',
    '  idPrefix,',
    '  initialWidth,',
    '  interactive = true,',
    '  onHydrated,',
    '  preview = false,',
    '  revision = 0,',
    '}: {',
    '  aspectRatio?: number',
    '  caseId: ChartsLandingCaseId',
    '  height?: number',
    '  idPrefix: string',
    '  initialWidth: number',
    '  interactive?: boolean',
    '  onHydrated?: () => void',
    '  preview?: boolean',
    '  revision?: number',
    '}) {',
    '  const chartProps = {',
    '    aspectRatio,',
    '    height,',
    '    idPrefix,',
    '    initialWidth,',
    '    interactive,',
    '    preview,',
    '    revision,',
    '  } satisfies CatalogChartProps',
    '  let chart: ReactNode',
    '',
    '  switch (caseId) {',
    ...cases,
    '  }',
    '',
    '  return (',
    '    <div',
    '      className="charts-catalog-chart relative h-full w-full overflow-visible"',
    '      data-chart-case={caseId}',
    '      style={{ height }}',
    '    >',
    '      {chart}',
    '    </div>',
    '  )',
    '}',
    '',
    'function ChartMounted({',
    '  children,',
    '  onMount,',
    '}: {',
    '  children: ReactNode',
    '  onMount?: () => void',
    '}) {',
    '  const didNotify = useRef(false)',
    '',
    '  useEffect(() => {',
    '    if (didNotify.current) return',
    '    didNotify.current = true',
    '    onMount?.()',
    '  }, [onMount])',
    '',
    '  return children',
    '}',
    '',
  ].join('\n')
}

export function loadCatalogCaseMetadata(metadataDirectory: string) {
  return readdirSync(metadataDirectory, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => join(metadataDirectory, entry.name, 'case.json'))
    .filter((caseFile) => existsSync(caseFile))
    .map((caseFile) => parseCatalogCaseMetadata(caseFile))
}

function parseCatalogCaseMetadata(caseFile: string): CatalogCaseMetadata {
  const value: unknown = JSON.parse(readFileSync(caseFile, 'utf8'))

  if (
    typeof value !== 'object' ||
    value === null ||
    !('id' in value) ||
    !('order' in value) ||
    typeof value.id !== 'string' ||
    typeof value.order !== 'number'
  ) {
    throw new Error(`Invalid catalog case metadata: ${caseFile}`)
  }

  return { id: value.id, order: value.order }
}

function getArgument(name: string) {
  const index = process.argv.indexOf(name)
  if (index === -1) return undefined

  const value = process.argv[index + 1]
  if (!value || value.startsWith('--')) {
    throw new Error(`${name} requires a value.`)
  }
  return value
}

function main() {
  const metadataDirectory = getArgument('--metadata-dir')
  const metadata = metadataDirectory
    ? loadCatalogCaseMetadata(resolve(metadataDirectory))
    : catalogCases
  const source = createChartsLandingCatalogSource(metadata)

  if (process.argv.includes('--check')) {
    if (
      !existsSync(outputFile) ||
      readFileSync(outputFile, 'utf8') !== source
    ) {
      throw new Error(
        'Charts landing catalog is stale. Run pnpm charts:generate-landing-catalog.',
      )
    }
    return
  }

  writeFileSync(outputFile, source)
}

const entryFile = process.argv[1]
if (entryFile && import.meta.url === pathToFileURL(entryFile).href) {
  main()
}
