import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs'
import { createHash } from 'node:crypto'
import { dirname, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

import { createElement } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import './pin-catalog-locale'
import { catalogCases } from '@tanstack/react-charts-catalog'
import type { ComponentType } from 'react'
import type { CatalogChartProps } from '@tanstack/react-charts-catalog'

type CatalogModule = {
  default: ComponentType<CatalogChartProps>
}

type ChartAssetTheme = {
  background: string
  foreground: string
  muted: string
  grid: string
  gridOpacity: string
  axisOpacity: string
  textOpacity: string
  series: ReadonlyArray<string>
}

const chartAssetThemes = {
  dark: {
    background: '#071219',
    foreground: '#d9edf1',
    muted: '#91a9b4',
    grid: '#d9edf1',
    gridOpacity: '0.13',
    axisOpacity: '0.28',
    textOpacity: '0.62',
    series: ['#61e8ff', '#ff806f', '#b9f227', '#c4a7ff', '#ffd85e', '#91a9b4'],
  },
  light: {
    background: '#ffffff',
    foreground: '#071219',
    muted: '#667c87',
    grid: '#071219',
    gridOpacity: '0.1',
    axisOpacity: '0.32',
    textOpacity: '0.6',
    series: ['#2497bd', '#e46244', '#39a84b', '#805ad5', '#e69a16', '#667c87'],
  },
} satisfies Record<'dark' | 'light', ChartAssetTheme>

const scriptDirectory = dirname(fileURLToPath(import.meta.url))
const repositoryRoot = resolve(scriptDirectory, '..')
const outputDirectory = resolve(repositoryRoot, 'public/images/charts/catalog')
const outputModule = resolve(
  repositoryRoot,
  'src/components/charts/chartsLandingCatalogAssets.ts',
)
const checkOnly = process.argv.includes('--check')

async function createAssets() {
  const files = new Map<string, string>()
  const revision = createHash('sha256')
  const orderedCases = [...catalogCases].sort(
    (left, right) => left.order - right.order,
  )

  for (const catalogCase of orderedCases) {
    const specifier = `@tanstack/react-charts-catalog/cases/${catalogCase.id}`
    const loaded: unknown = await import(specifier)
    if (!isCatalogModule(loaded)) {
      throw new TypeError(`Invalid catalog component: ${catalogCase.id}`)
    }

    const html = renderToStaticMarkup(
      createElement(loaded.default, {
        aspectRatio: 1.5,
        idPrefix: `charts-landing-gallery-${catalogCase.id}`,
        initialWidth: 288,
        interactive: false,
        preview: true,
      }),
    )
    const svg = themeSvg(extractChartSvg(html, catalogCase.id))
    const filename = `${catalogCase.id}.svg`

    files.set(filename, svg)
    revision.update(catalogCase.id).update('\0').update(svg).update('\0')
  }

  return { files, revision: revision.digest('hex').slice(0, 12) }
}

function isCatalogModule(value: unknown): value is CatalogModule {
  return (
    typeof value === 'object' &&
    value !== null &&
    'default' in value &&
    typeof value.default === 'function'
  )
}

function extractChartSvg(html: string, caseId: string) {
  const start = html.indexOf('<svg')
  const end = html.indexOf('</svg>', start)
  if (start === -1 || end === -1) {
    throw new Error(`Catalog case did not render an SVG: ${caseId}`)
  }

  const svg = html.slice(start, end + '</svg>'.length)
  if (!svg.includes('class="ts-chart"')) {
    throw new Error(`Catalog case did not render a chart SVG: ${caseId}`)
  }
  if (!svg.includes('viewBox="0 0 288 192"')) {
    throw new Error(`Catalog case rendered the wrong preview ratio: ${caseId}`)
  }
  return svg
}

function themeSvg(svg: string) {
  const namespacedSvg = svg.replace(
    '<svg',
    '<svg xmlns="http://www.w3.org/2000/svg"',
  )
  const rootEnd = namespacedSvg.indexOf('>')
  const styles = `<style>.ts-chart__legend{display:none}.ts-chart text{font-size:9px}${themeCss(chartAssetThemes.light)}@media(prefers-color-scheme:dark){${themeCss(chartAssetThemes.dark)}}</style>`

  return `${namespacedSvg.slice(0, rootEnd + 1)}${styles}${namespacedSvg.slice(rootEnd + 1)}`
}

function themeCss(theme: ChartAssetTheme) {
  const variables = [
    `--ts-chart-background:${theme.background}`,
    `--ts-chart-foreground:${theme.foreground}`,
    `--ts-chart-muted:${theme.muted}`,
    ...theme.series.map((color, index) => `--ts-chart-${index + 1}:${color}`),
  ].join(';')

  return `:root{${variables};color:${theme.foreground}}.ts-chart__grid{stroke:${theme.grid};stroke-opacity:${theme.gridOpacity}}.ts-chart__axes line,.ts-chart__axes path{stroke:${theme.foreground};stroke-opacity:${theme.axisOpacity}}.ts-chart__axes text{fill:${theme.foreground};fill-opacity:${theme.textOpacity}}`
}

function createAssetModule(revision: string) {
  return [
    '// Generated by pnpm charts:generate-landing-catalog.',
    '// Source: @tanstack/react-charts-catalog case components.',
    '',
    `export const chartsLandingCatalogAssetRevision = '${revision}'`,
    '',
  ].join('\n')
}

async function main() {
  const { files, revision } = await createAssets()
  const moduleSource = createAssetModule(revision)
  const existingFiles = existsSync(outputDirectory)
    ? readdirSync(outputDirectory).filter((filename) =>
        filename.endsWith('.svg'),
      )
    : []

  if (checkOnly) {
    if (
      !existsSync(outputModule) ||
      readFileSync(outputModule, 'utf8') !== moduleSource
    ) {
      throw new Error(
        'Charts landing catalog assets are stale. Run pnpm charts:generate-landing-catalog.',
      )
    }
    if (
      existingFiles.length !== files.size ||
      existingFiles.some(
        (filename) =>
          !files.has(filename) ||
          readFileSync(resolve(outputDirectory, filename), 'utf8') !==
            files.get(filename),
      )
    ) {
      throw new Error(
        'Charts landing SVG assets are stale. Run pnpm charts:generate-landing-catalog.',
      )
    }
    return
  }

  mkdirSync(outputDirectory, { recursive: true })
  for (const filename of existingFiles) {
    if (!files.has(filename)) unlinkSync(resolve(outputDirectory, filename))
  }
  for (const [filename, svg] of files) {
    writeFileSync(resolve(outputDirectory, filename), svg)
  }
  writeFileSync(outputModule, moduleSource)
}

const entryFile = process.argv[1]
if (entryFile && import.meta.url === pathToFileURL(entryFile).href) {
  await main()
}
