export const kineticDarkTheme = {
  background: 'transparent',
  foreground: '#eeebd4',
  grid: '#eeebd4',
  muted: '#aea691',
  palette: ['#61adbf', '#e06e49', '#69bc75'],
}

export const productSignals = [
  {
    effort: 12,
    forecast: 58,
    id: 'Query',
    impact: 91,
    month: 1,
    previous: 38,
    product: 'Query',
    segment: 'Core',
    size: 8,
    value: 48,
  },
  {
    effort: 18,
    forecast: 66,
    id: 'Router',
    impact: 82,
    month: 2,
    previous: 45,
    product: 'Router',
    segment: 'Core',
    size: 6,
    value: 56,
  },
  {
    effort: 24,
    forecast: 62,
    id: 'Table',
    impact: 77,
    month: 3,
    previous: 51,
    product: 'Table',
    segment: 'Data',
    size: 7,
    value: 54,
  },
  {
    effort: 31,
    forecast: 78,
    id: 'Form',
    impact: 69,
    month: 4,
    previous: 49,
    product: 'Form',
    segment: 'Data',
    size: 5,
    value: 64,
  },
  {
    effort: 16,
    forecast: 83,
    id: 'Start',
    impact: 87,
    month: 5,
    previous: 57,
    product: 'Start',
    segment: 'Runtime',
    size: 9,
    value: 71,
  },
  {
    effort: 27,
    forecast: 86,
    id: 'Virtual',
    impact: 73,
    month: 6,
    previous: 63,
    product: 'Virtual',
    segment: 'Runtime',
    size: 6,
    value: 78,
  },
  {
    effort: 10,
    forecast: 94,
    id: 'Store',
    impact: 94,
    month: 7,
    previous: 68,
    product: 'Store',
    segment: 'Core',
    size: 10,
    value: 86,
  },
  {
    effort: 22,
    forecast: 98,
    id: 'DB',
    impact: 80,
    month: 8,
    previous: 74,
    product: 'DB',
    segment: 'Data',
    size: 7,
    value: 91,
  },
]

export const productNames = productSignals.map((row) => row.product)
