/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopsRouteImport } from './routes/workshops'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TenetsRouteImport } from './routes/tenets'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SponsorsEmbedRouteImport } from './routes/sponsors-embed'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnersEmbedRouteImport } from './routes/partners-embed'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PaidSupportRouteImport } from './routes/paid-support'
import { Route as MerchRouteImport } from './routes/merch'
import { Route as MaintainersRouteImport } from './routes/maintainers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LibrariesRouteImport } from './routes/libraries'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as FeedbackLeaderboardRouteImport } from './routes/feedback-leaderboard'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as EthosRouteImport } from './routes/ethos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as BrandGuideRouteImport } from './routes/brand-guide'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as LibraryIdRouteRouteImport } from './routes/$libraryId/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatsIndexRouteImport } from './routes/stats/index'
import { Route as ShowcaseIndexRouteImport } from './routes/showcase/index'
import { Route as FeedIndexRouteImport } from './routes/feed.index'
import { Route as BuilderIndexRouteImport } from './routes/builder.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as LibraryIdIndexRouteImport } from './routes/$libraryId/index'
import { Route as ShowcaseSubmitRouteImport } from './routes/showcase/submit'
import { Route as ShowcaseIdRouteImport } from './routes/showcase/$id'
import { Route as OauthTokenRouteImport } from './routes/oauth/token'
import { Route as OauthRegisterRouteImport } from './routes/oauth/register'
import { Route as OauthAuthorizeRouteImport } from './routes/oauth/authorize'
import { Route as FeedIdRouteImport } from './routes/feed.$id'
import { Route as BuilderDocsRouteImport } from './routes/builder.docs'
import { Route as BlogSplatRouteImport } from './routes/blog.$'
import { Route as AuthSignoutRouteImport } from './routes/auth/signout'
import { Route as AuthPopupSuccessRouteImport } from './routes/auth/popup-success'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminNpmStatsRouteImport } from './routes/admin/npm-stats'
import { Route as AdminLoginsRouteImport } from './routes/admin/logins'
import { Route as AdminGithubStatsRouteImport } from './routes/admin/github-stats'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AccountSubmissionsRouteImport } from './routes/account/submissions'
import { Route as AccountNotesRouteImport } from './routes/account/notes'
import { Route as AccountIntegrationsRouteImport } from './routes/account/integrations'
import { Route as AccountFeedbackRouteImport } from './routes/account/feedback'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known/oauth-authorization-server'
import { Route as LibraryIdVersionRouteImport } from './routes/$libraryId/$version'
import { Route as StatsNpmIndexRouteImport } from './routes/stats/npm/index'
import { Route as ApiMcpIndexRouteImport } from './routes/api/mcp/index'
import { Route as AdminShowcasesIndexRouteImport } from './routes/admin/showcases.index'
import { Route as AdminRolesIndexRouteImport } from './routes/admin/roles.index'
import { Route as AdminNotesIndexRouteImport } from './routes/admin/notes.index'
import { Route as AdminFeedbackIndexRouteImport } from './routes/admin/feedback.index'
import { Route as AdminFeedIndexRouteImport } from './routes/admin/feed.index'
import { Route as AdminBannersIndexRouteImport } from './routes/admin/banners.index'
import { Route as LibraryIdVersionIndexRouteImport } from './routes/$libraryId/$version.index'
import { Route as StatsNpmPackagesRouteImport } from './routes/stats/npm/$packages'
import { Route as ShowcaseEditIdRouteImport } from './routes/showcase/edit.$id'
import { Route as AuthProviderStartRouteImport } from './routes/auth/$provider/start'
import { Route as ApiMcpSplatRouteImport } from './routes/api/mcp/$'
import { Route as ApiGithubWebhookRouteImport } from './routes/api/github/webhook'
import { Route as ApiExampleDeployRouteImport } from './routes/api/example/deploy'
import { Route as ApiDiscordInteractionsRouteImport } from './routes/api/discord/interactions'
import { Route as ApiDataPartnersRouteImport } from './routes/api/data/partners'
import { Route as ApiDataLibrariesRouteImport } from './routes/api/data/libraries'
import { Route as ApiBuilderValidateRouteImport } from './routes/api/builder/validate'
import { Route as ApiBuilderSuggestRouteImport } from './routes/api/builder/suggest'
import { Route as ApiBuilderLoadTemplateRouteImport } from './routes/api/builder/load-template'
import { Route as ApiBuilderLoadRemoteTemplateRouteImport } from './routes/api/builder/load-remote-template'
import { Route as ApiBuilderLoadRemoteAddonRouteImport } from './routes/api/builder/load-remote-addon'
import { Route as ApiBuilderFeaturesRouteImport } from './routes/api/builder/features'
import { Route as ApiBuilderFeatureArtifactsRouteImport } from './routes/api/builder/feature-artifacts'
import { Route as ApiBuilderDownloadRouteImport } from './routes/api/builder/download'
import { Route as ApiBuilderCompileAttributedRouteImport } from './routes/api/builder/compile-attributed'
import { Route as ApiBuilderCompileRouteImport } from './routes/api/builder/compile'
import { Route as ApiAdminSyncRouteImport } from './routes/api/admin/sync'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users.$userId'
import { Route as AdminShowcasesIdRouteImport } from './routes/admin/showcases_.$id'
import { Route as AdminRolesRoleIdRouteImport } from './routes/admin/roles.$roleId'
import { Route as AdminFeedbackIdRouteImport } from './routes/admin/feedback_.$id'
import { Route as AdminFeedIdRouteImport } from './routes/admin/feed.$id'
import { Route as AdminBannersIdRouteImport } from './routes/admin/banners.$id'
import { Route as LibraryIdVersionDocsRouteImport } from './routes/$libraryId/$version.docs'
import { Route as LibraryIdVersionDocsIndexRouteImport } from './routes/$libraryId/$version.docs.index'
import { Route as ApiBuilderDeployGithubRouteImport } from './routes/api/builder/deploy/github'
import { Route as ApiBuilderDeployCheckNameRouteImport } from './routes/api/builder/deploy/check-name'
import { Route as ApiAuthCallbackProviderRouteImport } from './routes/api/auth/callback/$provider'
import { Route as LibraryIdVersionDocsChar123Char125DotmdRouteImport } from './routes/$libraryId/$version.docs.{$}[.]md'
import { Route as LibraryIdVersionDocsNpmStatsRouteImport } from './routes/$libraryId/$version.docs.npm-stats'
import { Route as LibraryIdVersionDocsContributorsRouteImport } from './routes/$libraryId/$version.docs.contributors'
import { Route as LibraryIdVersionDocsCommunityResourcesRouteImport } from './routes/$libraryId/$version.docs.community-resources'
import { Route as LibraryIdVersionDocsSplatRouteImport } from './routes/$libraryId/$version.docs.$'
import { Route as LibraryIdVersionDocsFrameworkIndexRouteImport } from './routes/$libraryId/$version.docs.framework.index'
import { Route as LibraryIdVersionDocsFrameworkFrameworkIndexRouteImport } from './routes/$libraryId/$version.docs.framework.$framework.index'
import { Route as LibraryIdVersionDocsFrameworkFrameworkChar123Char125DotmdRouteImport } from './routes/$libraryId/$version.docs.framework.$framework.{$}[.]md'
import { Route as LibraryIdVersionDocsFrameworkFrameworkSplatRouteImport } from './routes/$libraryId/$version.docs.framework.$framework.$'
import { Route as LibraryIdVersionDocsFrameworkFrameworkExamplesSplatRouteImport } from './routes/$libraryId/$version.docs.framework.$framework.examples.$'

const WorkshopsRoute = WorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TenetsRoute = TenetsRouteImport.update({
  id: '/tenets',
  path: '/tenets',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsEmbedRoute = SponsorsEmbedRouteImport.update({
  id: '/sponsors-embed',
  path: '/sponsors-embed',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersEmbedRoute = PartnersEmbedRouteImport.update({
  id: '/partners-embed',
  path: '/partners-embed',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PaidSupportRoute = PaidSupportRouteImport.update({
  id: '/paid-support',
  path: '/paid-support',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchRoute = MerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintainersRoute = MaintainersRouteImport.update({
  id: '/maintainers',
  path: '/maintainers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesRoute = LibrariesRouteImport.update({
  id: '/libraries',
  path: '/libraries',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackLeaderboardRoute = FeedbackLeaderboardRouteImport.update({
  id: '/feedback-leaderboard',
  path: '/feedback-leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const EthosRoute = EthosRouteImport.update({
  id: '/ethos',
  path: '/ethos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandGuideRoute = BrandGuideRouteImport.update({
  id: '/brand-guide',
  path: '/brand-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIdRouteRoute = LibraryIdRouteRouteImport.update({
  id: '/$libraryId',
  path: '/$libraryId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIndexRoute = StatsIndexRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseIndexRoute = ShowcaseIndexRouteImport.update({
  id: '/showcase/',
  path: '/showcase/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedIndexRoute = FeedIndexRouteImport.update({
  id: '/feed/',
  path: '/feed/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderIndexRoute = BuilderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuilderRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const LibraryIdIndexRoute = LibraryIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryIdRouteRoute,
} as any)
const ShowcaseSubmitRoute = ShowcaseSubmitRouteImport.update({
  id: '/showcase/submit',
  path: '/showcase/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseIdRoute = ShowcaseIdRouteImport.update({
  id: '/showcase/$id',
  path: '/showcase/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthTokenRoute = OauthTokenRouteImport.update({
  id: '/oauth/token',
  path: '/oauth/token',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthRegisterRoute = OauthRegisterRouteImport.update({
  id: '/oauth/register',
  path: '/oauth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthAuthorizeRoute = OauthAuthorizeRouteImport.update({
  id: '/oauth/authorize',
  path: '/oauth/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedIdRoute = FeedIdRouteImport.update({
  id: '/feed/$id',
  path: '/feed/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderDocsRoute = BuilderDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => BuilderRoute,
} as any)
const BlogSplatRoute = BlogSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => BlogRoute,
} as any)
const AuthSignoutRoute = AuthSignoutRouteImport.update({
  id: '/auth/signout',
  path: '/auth/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPopupSuccessRoute = AuthPopupSuccessRouteImport.update({
  id: '/auth/popup-success',
  path: '/auth/popup-success',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNpmStatsRoute = AdminNpmStatsRouteImport.update({
  id: '/npm-stats',
  path: '/npm-stats',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginsRoute = AdminLoginsRouteImport.update({
  id: '/logins',
  path: '/logins',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGithubStatsRoute = AdminGithubStatsRouteImport.update({
  id: '/github-stats',
  path: '/github-stats',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountSubmissionsRoute = AccountSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AccountRoute,
} as any)
const AccountNotesRoute = AccountNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AccountRoute,
} as any)
const AccountIntegrationsRoute = AccountIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AccountRoute,
} as any)
const AccountFeedbackRoute = AccountFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AccountRoute,
} as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const LibraryIdVersionRoute = LibraryIdVersionRouteImport.update({
  id: '/$version',
  path: '/$version',
  getParentRoute: () => LibraryIdRouteRoute,
} as any)
const StatsNpmIndexRoute = StatsNpmIndexRouteImport.update({
  id: '/stats/npm/',
  path: '/stats/npm/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpIndexRoute = ApiMcpIndexRouteImport.update({
  id: '/api/mcp/',
  path: '/api/mcp/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShowcasesIndexRoute = AdminShowcasesIndexRouteImport.update({
  id: '/showcases/',
  path: '/showcases/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRolesIndexRoute = AdminRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotesIndexRoute = AdminNotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFeedbackIndexRoute = AdminFeedbackIndexRouteImport.update({
  id: '/feedback/',
  path: '/feedback/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFeedIndexRoute = AdminFeedIndexRouteImport.update({
  id: '/feed/',
  path: '/feed/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBannersIndexRoute = AdminBannersIndexRouteImport.update({
  id: '/banners/',
  path: '/banners/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LibraryIdVersionIndexRoute = LibraryIdVersionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryIdVersionRoute,
} as any)
const StatsNpmPackagesRoute = StatsNpmPackagesRouteImport.update({
  id: '/stats/npm/$packages',
  path: '/stats/npm/$packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseEditIdRoute = ShowcaseEditIdRouteImport.update({
  id: '/showcase/edit/$id',
  path: '/showcase/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProviderStartRoute = AuthProviderStartRouteImport.update({
  id: '/auth/$provider/start',
  path: '/auth/$provider/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpSplatRoute = ApiMcpSplatRouteImport.update({
  id: '/api/mcp/$',
  path: '/api/mcp/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubWebhookRoute = ApiGithubWebhookRouteImport.update({
  id: '/api/github/webhook',
  path: '/api/github/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExampleDeployRoute = ApiExampleDeployRouteImport.update({
  id: '/api/example/deploy',
  path: '/api/example/deploy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscordInteractionsRoute = ApiDiscordInteractionsRouteImport.update({
  id: '/api/discord/interactions',
  path: '/api/discord/interactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataPartnersRoute = ApiDataPartnersRouteImport.update({
  id: '/api/data/partners',
  path: '/api/data/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataLibrariesRoute = ApiDataLibrariesRouteImport.update({
  id: '/api/data/libraries',
  path: '/api/data/libraries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuilderValidateRoute = ApiBuilderValidateRouteImport.update({
  id: '/api/builder/validate',
  path: '/api/builder/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuilderSuggestRoute = ApiBuilderSuggestRouteImport.update({
  id: '/api/builder/suggest',
  path: '/api/builder/suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuilderLoadTemplateRoute = ApiBuilderLoadTemplateRouteImport.update({
  id: '/api/builder/load-template',
  path: '/api/builder/load-template',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuilderLoadRemoteTemplateRoute =
  ApiBuilderLoadRemoteTemplateRouteImport.update({
    id: '/api/builder/load-remote-template',
    path: '/api/builder/load-remote-template',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBuilderLoadRemoteAddonRoute =
  ApiBuilderLoadRemoteAddonRouteImport.update({
    id: '/api/builder/load-remote-addon',
    path: '/api/builder/load-remote-addon',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBuilderFeaturesRoute = ApiBuilderFeaturesRouteImport.update({
  id: '/api/builder/features',
  path: '/api/builder/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuilderFeatureArtifactsRoute =
  ApiBuilderFeatureArtifactsRouteImport.update({
    id: '/api/builder/feature-artifacts',
    path: '/api/builder/feature-artifacts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBuilderDownloadRoute = ApiBuilderDownloadRouteImport.update({
  id: '/api/builder/download',
  path: '/api/builder/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuilderCompileAttributedRoute =
  ApiBuilderCompileAttributedRouteImport.update({
    id: '/api/builder/compile-attributed',
    path: '/api/builder/compile-attributed',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBuilderCompileRoute = ApiBuilderCompileRouteImport.update({
  id: '/api/builder/compile',
  path: '/api/builder/compile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSyncRoute = ApiAdminSyncRouteImport.update({
  id: '/api/admin/sync',
  path: '/api/admin/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminShowcasesIdRoute = AdminShowcasesIdRouteImport.update({
  id: '/showcases_/$id',
  path: '/showcases/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRolesRoleIdRoute = AdminRolesRoleIdRouteImport.update({
  id: '/roles/$roleId',
  path: '/roles/$roleId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFeedbackIdRoute = AdminFeedbackIdRouteImport.update({
  id: '/feedback_/$id',
  path: '/feedback/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFeedIdRoute = AdminFeedIdRouteImport.update({
  id: '/feed/$id',
  path: '/feed/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBannersIdRoute = AdminBannersIdRouteImport.update({
  id: '/banners/$id',
  path: '/banners/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LibraryIdVersionDocsRoute = LibraryIdVersionDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => LibraryIdVersionRoute,
} as any)
const LibraryIdVersionDocsIndexRoute =
  LibraryIdVersionDocsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LibraryIdVersionDocsRoute,
  } as any)
const ApiBuilderDeployGithubRoute = ApiBuilderDeployGithubRouteImport.update({
  id: '/api/builder/deploy/github',
  path: '/api/builder/deploy/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuilderDeployCheckNameRoute =
  ApiBuilderDeployCheckNameRouteImport.update({
    id: '/api/builder/deploy/check-name',
    path: '/api/builder/deploy/check-name',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthCallbackProviderRoute = ApiAuthCallbackProviderRouteImport.update({
  id: '/api/auth/callback/$provider',
  path: '/api/auth/callback/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIdVersionDocsChar123Char125DotmdRoute =
  LibraryIdVersionDocsChar123Char125DotmdRouteImport.update({
    id: '/{$}.md',
    path: '/{$}.md',
    getParentRoute: () => LibraryIdVersionDocsRoute,
  } as any)
const LibraryIdVersionDocsNpmStatsRoute =
  LibraryIdVersionDocsNpmStatsRouteImport.update({
    id: '/npm-stats',
    path: '/npm-stats',
    getParentRoute: () => LibraryIdVersionDocsRoute,
  } as any)
const LibraryIdVersionDocsContributorsRoute =
  LibraryIdVersionDocsContributorsRouteImport.update({
    id: '/contributors',
    path: '/contributors',
    getParentRoute: () => LibraryIdVersionDocsRoute,
  } as any)
const LibraryIdVersionDocsCommunityResourcesRoute =
  LibraryIdVersionDocsCommunityResourcesRouteImport.update({
    id: '/community-resources',
    path: '/community-resources',
    getParentRoute: () => LibraryIdVersionDocsRoute,
  } as any)
const LibraryIdVersionDocsSplatRoute =
  LibraryIdVersionDocsSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => LibraryIdVersionDocsRoute,
  } as any)
const LibraryIdVersionDocsFrameworkIndexRoute =
  LibraryIdVersionDocsFrameworkIndexRouteImport.update({
    id: '/framework/',
    path: '/framework/',
    getParentRoute: () => LibraryIdVersionDocsRoute,
  } as any)
const LibraryIdVersionDocsFrameworkFrameworkIndexRoute =
  LibraryIdVersionDocsFrameworkFrameworkIndexRouteImport.update({
    id: '/framework/$framework/',
    path: '/framework/$framework/',
    getParentRoute: () => LibraryIdVersionDocsRoute,
  } as any)
const LibraryIdVersionDocsFrameworkFrameworkChar123Char125DotmdRoute =
  LibraryIdVersionDocsFrameworkFrameworkChar123Char125DotmdRouteImport.update({
    id: '/framework/$framework/{$}.md',
    path: '/framework/$framework/{$}.md',
    getParentRoute: () => LibraryIdVersionDocsRoute,
  } as any)
const LibraryIdVersionDocsFrameworkFrameworkSplatRoute =
  LibraryIdVersionDocsFrameworkFrameworkSplatRouteImport.update({
    id: '/framework/$framework/$',
    path: '/framework/$framework/$',
    getParentRoute: () => LibraryIdVersionDocsRoute,
  } as any)
const LibraryIdVersionDocsFrameworkFrameworkExamplesSplatRoute =
  LibraryIdVersionDocsFrameworkFrameworkExamplesSplatRouteImport.update({
    id: '/framework/$framework/examples/$',
    path: '/framework/$framework/examples/$',
    getParentRoute: () => LibraryIdVersionDocsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$libraryId': typeof LibraryIdRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/ads': typeof AdsRoute
  '/blog': typeof BlogRouteWithChildren
  '/brand-guide': typeof BrandGuideRoute
  '/builder': typeof BuilderRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/ethos': typeof EthosRoute
  '/explore': typeof ExploreRoute
  '/feedback-leaderboard': typeof FeedbackLeaderboardRoute
  '/learn': typeof LearnRoute
  '/libraries': typeof LibrariesRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/maintainers': typeof MaintainersRoute
  '/merch': typeof MerchRoute
  '/paid-support': typeof PaidSupportRoute
  '/partners': typeof PartnersRoute
  '/partners-embed': typeof PartnersEmbedRoute
  '/privacy': typeof PrivacyRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sponsors-embed': typeof SponsorsEmbedRoute
  '/support': typeof SupportRoute
  '/tenets': typeof TenetsRoute
  '/terms': typeof TermsRoute
  '/workshops': typeof WorkshopsRoute
  '/$libraryId/$version': typeof LibraryIdVersionRouteWithChildren
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/account/feedback': typeof AccountFeedbackRoute
  '/account/integrations': typeof AccountIntegrationsRoute
  '/account/notes': typeof AccountNotesRoute
  '/account/submissions': typeof AccountSubmissionsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/github-stats': typeof AdminGithubStatsRoute
  '/admin/logins': typeof AdminLoginsRoute
  '/admin/npm-stats': typeof AdminNpmStatsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/auth/popup-success': typeof AuthPopupSuccessRoute
  '/auth/signout': typeof AuthSignoutRoute
  '/blog/$': typeof BlogSplatRoute
  '/builder/docs': typeof BuilderDocsRoute
  '/feed/$id': typeof FeedIdRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/register': typeof OauthRegisterRoute
  '/oauth/token': typeof OauthTokenRoute
  '/showcase/$id': typeof ShowcaseIdRoute
  '/showcase/submit': typeof ShowcaseSubmitRoute
  '/$libraryId/': typeof LibraryIdIndexRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/builder/': typeof BuilderIndexRoute
  '/feed/': typeof FeedIndexRoute
  '/showcase/': typeof ShowcaseIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/$libraryId/$version/docs': typeof LibraryIdVersionDocsRouteWithChildren
  '/admin/banners/$id': typeof AdminBannersIdRoute
  '/admin/feed/$id': typeof AdminFeedIdRoute
  '/admin/feedback/$id': typeof AdminFeedbackIdRoute
  '/admin/roles/$roleId': typeof AdminRolesRoleIdRoute
  '/admin/showcases/$id': typeof AdminShowcasesIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/admin/sync': typeof ApiAdminSyncRoute
  '/api/builder/compile': typeof ApiBuilderCompileRoute
  '/api/builder/compile-attributed': typeof ApiBuilderCompileAttributedRoute
  '/api/builder/download': typeof ApiBuilderDownloadRoute
  '/api/builder/feature-artifacts': typeof ApiBuilderFeatureArtifactsRoute
  '/api/builder/features': typeof ApiBuilderFeaturesRoute
  '/api/builder/load-remote-addon': typeof ApiBuilderLoadRemoteAddonRoute
  '/api/builder/load-remote-template': typeof ApiBuilderLoadRemoteTemplateRoute
  '/api/builder/load-template': typeof ApiBuilderLoadTemplateRoute
  '/api/builder/suggest': typeof ApiBuilderSuggestRoute
  '/api/builder/validate': typeof ApiBuilderValidateRoute
  '/api/data/libraries': typeof ApiDataLibrariesRoute
  '/api/data/partners': typeof ApiDataPartnersRoute
  '/api/discord/interactions': typeof ApiDiscordInteractionsRoute
  '/api/example/deploy': typeof ApiExampleDeployRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/mcp/$': typeof ApiMcpSplatRoute
  '/auth/$provider/start': typeof AuthProviderStartRoute
  '/showcase/edit/$id': typeof ShowcaseEditIdRoute
  '/stats/npm/$packages': typeof StatsNpmPackagesRoute
  '/$libraryId/$version/': typeof LibraryIdVersionIndexRoute
  '/admin/banners/': typeof AdminBannersIndexRoute
  '/admin/feed/': typeof AdminFeedIndexRoute
  '/admin/feedback/': typeof AdminFeedbackIndexRoute
  '/admin/notes/': typeof AdminNotesIndexRoute
  '/admin/roles/': typeof AdminRolesIndexRoute
  '/admin/showcases/': typeof AdminShowcasesIndexRoute
  '/api/mcp/': typeof ApiMcpIndexRoute
  '/stats/npm/': typeof StatsNpmIndexRoute
  '/$libraryId/$version/docs/$': typeof LibraryIdVersionDocsSplatRoute
  '/$libraryId/$version/docs/community-resources': typeof LibraryIdVersionDocsCommunityResourcesRoute
  '/$libraryId/$version/docs/contributors': typeof LibraryIdVersionDocsContributorsRoute
  '/$libraryId/$version/docs/npm-stats': typeof LibraryIdVersionDocsNpmStatsRoute
  '/$libraryId/$version/docs/{$}.md': typeof LibraryIdVersionDocsChar123Char125DotmdRoute
  '/api/auth/callback/$provider': typeof ApiAuthCallbackProviderRoute
  '/api/builder/deploy/check-name': typeof ApiBuilderDeployCheckNameRoute
  '/api/builder/deploy/github': typeof ApiBuilderDeployGithubRoute
  '/$libraryId/$version/docs/': typeof LibraryIdVersionDocsIndexRoute
  '/$libraryId/$version/docs/framework/': typeof LibraryIdVersionDocsFrameworkIndexRoute
  '/$libraryId/$version/docs/framework/$framework/$': typeof LibraryIdVersionDocsFrameworkFrameworkSplatRoute
  '/$libraryId/$version/docs/framework/$framework/{$}.md': typeof LibraryIdVersionDocsFrameworkFrameworkChar123Char125DotmdRoute
  '/$libraryId/$version/docs/framework/$framework/': typeof LibraryIdVersionDocsFrameworkFrameworkIndexRoute
  '/$libraryId/$version/docs/framework/$framework/examples/$': typeof LibraryIdVersionDocsFrameworkFrameworkExamplesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/brand-guide': typeof BrandGuideRoute
  '/dashboard': typeof DashboardRoute
  '/ethos': typeof EthosRoute
  '/explore': typeof ExploreRoute
  '/feedback-leaderboard': typeof FeedbackLeaderboardRoute
  '/learn': typeof LearnRoute
  '/libraries': typeof LibrariesRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/maintainers': typeof MaintainersRoute
  '/merch': typeof MerchRoute
  '/paid-support': typeof PaidSupportRoute
  '/partners': typeof PartnersRoute
  '/partners-embed': typeof PartnersEmbedRoute
  '/privacy': typeof PrivacyRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sponsors-embed': typeof SponsorsEmbedRoute
  '/support': typeof SupportRoute
  '/tenets': typeof TenetsRoute
  '/terms': typeof TermsRoute
  '/workshops': typeof WorkshopsRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/account/feedback': typeof AccountFeedbackRoute
  '/account/integrations': typeof AccountIntegrationsRoute
  '/account/notes': typeof AccountNotesRoute
  '/account/submissions': typeof AccountSubmissionsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/github-stats': typeof AdminGithubStatsRoute
  '/admin/logins': typeof AdminLoginsRoute
  '/admin/npm-stats': typeof AdminNpmStatsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/auth/popup-success': typeof AuthPopupSuccessRoute
  '/auth/signout': typeof AuthSignoutRoute
  '/blog/$': typeof BlogSplatRoute
  '/builder/docs': typeof BuilderDocsRoute
  '/feed/$id': typeof FeedIdRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/register': typeof OauthRegisterRoute
  '/oauth/token': typeof OauthTokenRoute
  '/showcase/$id': typeof ShowcaseIdRoute
  '/showcase/submit': typeof ShowcaseSubmitRoute
  '/$libraryId': typeof LibraryIdIndexRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/builder': typeof BuilderIndexRoute
  '/feed': typeof FeedIndexRoute
  '/showcase': typeof ShowcaseIndexRoute
  '/stats': typeof StatsIndexRoute
  '/admin/banners/$id': typeof AdminBannersIdRoute
  '/admin/feed/$id': typeof AdminFeedIdRoute
  '/admin/feedback/$id': typeof AdminFeedbackIdRoute
  '/admin/roles/$roleId': typeof AdminRolesRoleIdRoute
  '/admin/showcases/$id': typeof AdminShowcasesIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/admin/sync': typeof ApiAdminSyncRoute
  '/api/builder/compile': typeof ApiBuilderCompileRoute
  '/api/builder/compile-attributed': typeof ApiBuilderCompileAttributedRoute
  '/api/builder/download': typeof ApiBuilderDownloadRoute
  '/api/builder/feature-artifacts': typeof ApiBuilderFeatureArtifactsRoute
  '/api/builder/features': typeof ApiBuilderFeaturesRoute
  '/api/builder/load-remote-addon': typeof ApiBuilderLoadRemoteAddonRoute
  '/api/builder/load-remote-template': typeof ApiBuilderLoadRemoteTemplateRoute
  '/api/builder/load-template': typeof ApiBuilderLoadTemplateRoute
  '/api/builder/suggest': typeof ApiBuilderSuggestRoute
  '/api/builder/validate': typeof ApiBuilderValidateRoute
  '/api/data/libraries': typeof ApiDataLibrariesRoute
  '/api/data/partners': typeof ApiDataPartnersRoute
  '/api/discord/interactions': typeof ApiDiscordInteractionsRoute
  '/api/example/deploy': typeof ApiExampleDeployRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/mcp/$': typeof ApiMcpSplatRoute
  '/auth/$provider/start': typeof AuthProviderStartRoute
  '/showcase/edit/$id': typeof ShowcaseEditIdRoute
  '/stats/npm/$packages': typeof StatsNpmPackagesRoute
  '/$libraryId/$version': typeof LibraryIdVersionIndexRoute
  '/admin/banners': typeof AdminBannersIndexRoute
  '/admin/feed': typeof AdminFeedIndexRoute
  '/admin/feedback': typeof AdminFeedbackIndexRoute
  '/admin/notes': typeof AdminNotesIndexRoute
  '/admin/roles': typeof AdminRolesIndexRoute
  '/admin/showcases': typeof AdminShowcasesIndexRoute
  '/api/mcp': typeof ApiMcpIndexRoute
  '/stats/npm': typeof StatsNpmIndexRoute
  '/$libraryId/$version/docs/$': typeof LibraryIdVersionDocsSplatRoute
  '/$libraryId/$version/docs/community-resources': typeof LibraryIdVersionDocsCommunityResourcesRoute
  '/$libraryId/$version/docs/contributors': typeof LibraryIdVersionDocsContributorsRoute
  '/$libraryId/$version/docs/npm-stats': typeof LibraryIdVersionDocsNpmStatsRoute
  '/$libraryId/$version/docs/{$}.md': typeof LibraryIdVersionDocsChar123Char125DotmdRoute
  '/api/auth/callback/$provider': typeof ApiAuthCallbackProviderRoute
  '/api/builder/deploy/check-name': typeof ApiBuilderDeployCheckNameRoute
  '/api/builder/deploy/github': typeof ApiBuilderDeployGithubRoute
  '/$libraryId/$version/docs': typeof LibraryIdVersionDocsIndexRoute
  '/$libraryId/$version/docs/framework': typeof LibraryIdVersionDocsFrameworkIndexRoute
  '/$libraryId/$version/docs/framework/$framework/$': typeof LibraryIdVersionDocsFrameworkFrameworkSplatRoute
  '/$libraryId/$version/docs/framework/$framework/{$}.md': typeof LibraryIdVersionDocsFrameworkFrameworkChar123Char125DotmdRoute
  '/$libraryId/$version/docs/framework/$framework': typeof LibraryIdVersionDocsFrameworkFrameworkIndexRoute
  '/$libraryId/$version/docs/framework/$framework/examples/$': typeof LibraryIdVersionDocsFrameworkFrameworkExamplesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$libraryId': typeof LibraryIdRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/ads': typeof AdsRoute
  '/blog': typeof BlogRouteWithChildren
  '/brand-guide': typeof BrandGuideRoute
  '/builder': typeof BuilderRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/ethos': typeof EthosRoute
  '/explore': typeof ExploreRoute
  '/feedback-leaderboard': typeof FeedbackLeaderboardRoute
  '/learn': typeof LearnRoute
  '/libraries': typeof LibrariesRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/maintainers': typeof MaintainersRoute
  '/merch': typeof MerchRoute
  '/paid-support': typeof PaidSupportRoute
  '/partners': typeof PartnersRoute
  '/partners-embed': typeof PartnersEmbedRoute
  '/privacy': typeof PrivacyRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sponsors-embed': typeof SponsorsEmbedRoute
  '/support': typeof SupportRoute
  '/tenets': typeof TenetsRoute
  '/terms': typeof TermsRoute
  '/workshops': typeof WorkshopsRoute
  '/$libraryId/$version': typeof LibraryIdVersionRouteWithChildren
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/account/feedback': typeof AccountFeedbackRoute
  '/account/integrations': typeof AccountIntegrationsRoute
  '/account/notes': typeof AccountNotesRoute
  '/account/submissions': typeof AccountSubmissionsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/github-stats': typeof AdminGithubStatsRoute
  '/admin/logins': typeof AdminLoginsRoute
  '/admin/npm-stats': typeof AdminNpmStatsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/auth/popup-success': typeof AuthPopupSuccessRoute
  '/auth/signout': typeof AuthSignoutRoute
  '/blog/$': typeof BlogSplatRoute
  '/builder/docs': typeof BuilderDocsRoute
  '/feed/$id': typeof FeedIdRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/register': typeof OauthRegisterRoute
  '/oauth/token': typeof OauthTokenRoute
  '/showcase/$id': typeof ShowcaseIdRoute
  '/showcase/submit': typeof ShowcaseSubmitRoute
  '/$libraryId/': typeof LibraryIdIndexRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/builder/': typeof BuilderIndexRoute
  '/feed/': typeof FeedIndexRoute
  '/showcase/': typeof ShowcaseIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/$libraryId/$version/docs': typeof LibraryIdVersionDocsRouteWithChildren
  '/admin/banners/$id': typeof AdminBannersIdRoute
  '/admin/feed/$id': typeof AdminFeedIdRoute
  '/admin/feedback_/$id': typeof AdminFeedbackIdRoute
  '/admin/roles/$roleId': typeof AdminRolesRoleIdRoute
  '/admin/showcases_/$id': typeof AdminShowcasesIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/admin/sync': typeof ApiAdminSyncRoute
  '/api/builder/compile': typeof ApiBuilderCompileRoute
  '/api/builder/compile-attributed': typeof ApiBuilderCompileAttributedRoute
  '/api/builder/download': typeof ApiBuilderDownloadRoute
  '/api/builder/feature-artifacts': typeof ApiBuilderFeatureArtifactsRoute
  '/api/builder/features': typeof ApiBuilderFeaturesRoute
  '/api/builder/load-remote-addon': typeof ApiBuilderLoadRemoteAddonRoute
  '/api/builder/load-remote-template': typeof ApiBuilderLoadRemoteTemplateRoute
  '/api/builder/load-template': typeof ApiBuilderLoadTemplateRoute
  '/api/builder/suggest': typeof ApiBuilderSuggestRoute
  '/api/builder/validate': typeof ApiBuilderValidateRoute
  '/api/data/libraries': typeof ApiDataLibrariesRoute
  '/api/data/partners': typeof ApiDataPartnersRoute
  '/api/discord/interactions': typeof ApiDiscordInteractionsRoute
  '/api/example/deploy': typeof ApiExampleDeployRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/mcp/$': typeof ApiMcpSplatRoute
  '/auth/$provider/start': typeof AuthProviderStartRoute
  '/showcase/edit/$id': typeof ShowcaseEditIdRoute
  '/stats/npm/$packages': typeof StatsNpmPackagesRoute
  '/$libraryId/$version/': typeof LibraryIdVersionIndexRoute
  '/admin/banners/': typeof AdminBannersIndexRoute
  '/admin/feed/': typeof AdminFeedIndexRoute
  '/admin/feedback/': typeof AdminFeedbackIndexRoute
  '/admin/notes/': typeof AdminNotesIndexRoute
  '/admin/roles/': typeof AdminRolesIndexRoute
  '/admin/showcases/': typeof AdminShowcasesIndexRoute
  '/api/mcp/': typeof ApiMcpIndexRoute
  '/stats/npm/': typeof StatsNpmIndexRoute
  '/$libraryId/$version/docs/$': typeof LibraryIdVersionDocsSplatRoute
  '/$libraryId/$version/docs/community-resources': typeof LibraryIdVersionDocsCommunityResourcesRoute
  '/$libraryId/$version/docs/contributors': typeof LibraryIdVersionDocsContributorsRoute
  '/$libraryId/$version/docs/npm-stats': typeof LibraryIdVersionDocsNpmStatsRoute
  '/$libraryId/$version/docs/{$}.md': typeof LibraryIdVersionDocsChar123Char125DotmdRoute
  '/api/auth/callback/$provider': typeof ApiAuthCallbackProviderRoute
  '/api/builder/deploy/check-name': typeof ApiBuilderDeployCheckNameRoute
  '/api/builder/deploy/github': typeof ApiBuilderDeployGithubRoute
  '/$libraryId/$version/docs/': typeof LibraryIdVersionDocsIndexRoute
  '/$libraryId/$version/docs/framework/': typeof LibraryIdVersionDocsFrameworkIndexRoute
  '/$libraryId/$version/docs/framework/$framework/$': typeof LibraryIdVersionDocsFrameworkFrameworkSplatRoute
  '/$libraryId/$version/docs/framework/$framework/{$}.md': typeof LibraryIdVersionDocsFrameworkFrameworkChar123Char125DotmdRoute
  '/$libraryId/$version/docs/framework/$framework/': typeof LibraryIdVersionDocsFrameworkFrameworkIndexRoute
  '/$libraryId/$version/docs/framework/$framework/examples/$': typeof LibraryIdVersionDocsFrameworkFrameworkExamplesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$libraryId'
    | '/admin'
    | '/account'
    | '/ads'
    | '/blog'
    | '/brand-guide'
    | '/builder'
    | '/dashboard'
    | '/ethos'
    | '/explore'
    | '/feedback-leaderboard'
    | '/learn'
    | '/libraries'
    | '/llms.txt'
    | '/login'
    | '/maintainers'
    | '/merch'
    | '/paid-support'
    | '/partners'
    | '/partners-embed'
    | '/privacy'
    | '/rss.xml'
    | '/sponsors-embed'
    | '/support'
    | '/tenets'
    | '/terms'
    | '/workshops'
    | '/$libraryId/$version'
    | '/.well-known/oauth-authorization-server'
    | '/account/feedback'
    | '/account/integrations'
    | '/account/notes'
    | '/account/submissions'
    | '/admin/audit'
    | '/admin/github-stats'
    | '/admin/logins'
    | '/admin/npm-stats'
    | '/admin/users'
    | '/api/uploadthing'
    | '/auth/popup-success'
    | '/auth/signout'
    | '/blog/$'
    | '/builder/docs'
    | '/feed/$id'
    | '/oauth/authorize'
    | '/oauth/register'
    | '/oauth/token'
    | '/showcase/$id'
    | '/showcase/submit'
    | '/$libraryId/'
    | '/account/'
    | '/admin/'
    | '/blog/'
    | '/builder/'
    | '/feed/'
    | '/showcase/'
    | '/stats/'
    | '/$libraryId/$version/docs'
    | '/admin/banners/$id'
    | '/admin/feed/$id'
    | '/admin/feedback/$id'
    | '/admin/roles/$roleId'
    | '/admin/showcases/$id'
    | '/admin/users/$userId'
    | '/api/admin/sync'
    | '/api/builder/compile'
    | '/api/builder/compile-attributed'
    | '/api/builder/download'
    | '/api/builder/feature-artifacts'
    | '/api/builder/features'
    | '/api/builder/load-remote-addon'
    | '/api/builder/load-remote-template'
    | '/api/builder/load-template'
    | '/api/builder/suggest'
    | '/api/builder/validate'
    | '/api/data/libraries'
    | '/api/data/partners'
    | '/api/discord/interactions'
    | '/api/example/deploy'
    | '/api/github/webhook'
    | '/api/mcp/$'
    | '/auth/$provider/start'
    | '/showcase/edit/$id'
    | '/stats/npm/$packages'
    | '/$libraryId/$version/'
    | '/admin/banners/'
    | '/admin/feed/'
    | '/admin/feedback/'
    | '/admin/notes/'
    | '/admin/roles/'
    | '/admin/showcases/'
    | '/api/mcp/'
    | '/stats/npm/'
    | '/$libraryId/$version/docs/$'
    | '/$libraryId/$version/docs/community-resources'
    | '/$libraryId/$version/docs/contributors'
    | '/$libraryId/$version/docs/npm-stats'
    | '/$libraryId/$version/docs/{$}.md'
    | '/api/auth/callback/$provider'
    | '/api/builder/deploy/check-name'
    | '/api/builder/deploy/github'
    | '/$libraryId/$version/docs/'
    | '/$libraryId/$version/docs/framework/'
    | '/$libraryId/$version/docs/framework/$framework/$'
    | '/$libraryId/$version/docs/framework/$framework/{$}.md'
    | '/$libraryId/$version/docs/framework/$framework/'
    | '/$libraryId/$version/docs/framework/$framework/examples/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ads'
    | '/brand-guide'
    | '/dashboard'
    | '/ethos'
    | '/explore'
    | '/feedback-leaderboard'
    | '/learn'
    | '/libraries'
    | '/llms.txt'
    | '/login'
    | '/maintainers'
    | '/merch'
    | '/paid-support'
    | '/partners'
    | '/partners-embed'
    | '/privacy'
    | '/rss.xml'
    | '/sponsors-embed'
    | '/support'
    | '/tenets'
    | '/terms'
    | '/workshops'
    | '/.well-known/oauth-authorization-server'
    | '/account/feedback'
    | '/account/integrations'
    | '/account/notes'
    | '/account/submissions'
    | '/admin/audit'
    | '/admin/github-stats'
    | '/admin/logins'
    | '/admin/npm-stats'
    | '/admin/users'
    | '/api/uploadthing'
    | '/auth/popup-success'
    | '/auth/signout'
    | '/blog/$'
    | '/builder/docs'
    | '/feed/$id'
    | '/oauth/authorize'
    | '/oauth/register'
    | '/oauth/token'
    | '/showcase/$id'
    | '/showcase/submit'
    | '/$libraryId'
    | '/account'
    | '/admin'
    | '/blog'
    | '/builder'
    | '/feed'
    | '/showcase'
    | '/stats'
    | '/admin/banners/$id'
    | '/admin/feed/$id'
    | '/admin/feedback/$id'
    | '/admin/roles/$roleId'
    | '/admin/showcases/$id'
    | '/admin/users/$userId'
    | '/api/admin/sync'
    | '/api/builder/compile'
    | '/api/builder/compile-attributed'
    | '/api/builder/download'
    | '/api/builder/feature-artifacts'
    | '/api/builder/features'
    | '/api/builder/load-remote-addon'
    | '/api/builder/load-remote-template'
    | '/api/builder/load-template'
    | '/api/builder/suggest'
    | '/api/builder/validate'
    | '/api/data/libraries'
    | '/api/data/partners'
    | '/api/discord/interactions'
    | '/api/example/deploy'
    | '/api/github/webhook'
    | '/api/mcp/$'
    | '/auth/$provider/start'
    | '/showcase/edit/$id'
    | '/stats/npm/$packages'
    | '/$libraryId/$version'
    | '/admin/banners'
    | '/admin/feed'
    | '/admin/feedback'
    | '/admin/notes'
    | '/admin/roles'
    | '/admin/showcases'
    | '/api/mcp'
    | '/stats/npm'
    | '/$libraryId/$version/docs/$'
    | '/$libraryId/$version/docs/community-resources'
    | '/$libraryId/$version/docs/contributors'
    | '/$libraryId/$version/docs/npm-stats'
    | '/$libraryId/$version/docs/{$}.md'
    | '/api/auth/callback/$provider'
    | '/api/builder/deploy/check-name'
    | '/api/builder/deploy/github'
    | '/$libraryId/$version/docs'
    | '/$libraryId/$version/docs/framework'
    | '/$libraryId/$version/docs/framework/$framework/$'
    | '/$libraryId/$version/docs/framework/$framework/{$}.md'
    | '/$libraryId/$version/docs/framework/$framework'
    | '/$libraryId/$version/docs/framework/$framework/examples/$'
  id:
    | '__root__'
    | '/'
    | '/$libraryId'
    | '/admin'
    | '/account'
    | '/ads'
    | '/blog'
    | '/brand-guide'
    | '/builder'
    | '/dashboard'
    | '/ethos'
    | '/explore'
    | '/feedback-leaderboard'
    | '/learn'
    | '/libraries'
    | '/llms.txt'
    | '/login'
    | '/maintainers'
    | '/merch'
    | '/paid-support'
    | '/partners'
    | '/partners-embed'
    | '/privacy'
    | '/rss.xml'
    | '/sponsors-embed'
    | '/support'
    | '/tenets'
    | '/terms'
    | '/workshops'
    | '/$libraryId/$version'
    | '/.well-known/oauth-authorization-server'
    | '/account/feedback'
    | '/account/integrations'
    | '/account/notes'
    | '/account/submissions'
    | '/admin/audit'
    | '/admin/github-stats'
    | '/admin/logins'
    | '/admin/npm-stats'
    | '/admin/users'
    | '/api/uploadthing'
    | '/auth/popup-success'
    | '/auth/signout'
    | '/blog/$'
    | '/builder/docs'
    | '/feed/$id'
    | '/oauth/authorize'
    | '/oauth/register'
    | '/oauth/token'
    | '/showcase/$id'
    | '/showcase/submit'
    | '/$libraryId/'
    | '/account/'
    | '/admin/'
    | '/blog/'
    | '/builder/'
    | '/feed/'
    | '/showcase/'
    | '/stats/'
    | '/$libraryId/$version/docs'
    | '/admin/banners/$id'
    | '/admin/feed/$id'
    | '/admin/feedback_/$id'
    | '/admin/roles/$roleId'
    | '/admin/showcases_/$id'
    | '/admin/users/$userId'
    | '/api/admin/sync'
    | '/api/builder/compile'
    | '/api/builder/compile-attributed'
    | '/api/builder/download'
    | '/api/builder/feature-artifacts'
    | '/api/builder/features'
    | '/api/builder/load-remote-addon'
    | '/api/builder/load-remote-template'
    | '/api/builder/load-template'
    | '/api/builder/suggest'
    | '/api/builder/validate'
    | '/api/data/libraries'
    | '/api/data/partners'
    | '/api/discord/interactions'
    | '/api/example/deploy'
    | '/api/github/webhook'
    | '/api/mcp/$'
    | '/auth/$provider/start'
    | '/showcase/edit/$id'
    | '/stats/npm/$packages'
    | '/$libraryId/$version/'
    | '/admin/banners/'
    | '/admin/feed/'
    | '/admin/feedback/'
    | '/admin/notes/'
    | '/admin/roles/'
    | '/admin/showcases/'
    | '/api/mcp/'
    | '/stats/npm/'
    | '/$libraryId/$version/docs/$'
    | '/$libraryId/$version/docs/community-resources'
    | '/$libraryId/$version/docs/contributors'
    | '/$libraryId/$version/docs/npm-stats'
    | '/$libraryId/$version/docs/{$}.md'
    | '/api/auth/callback/$provider'
    | '/api/builder/deploy/check-name'
    | '/api/builder/deploy/github'
    | '/$libraryId/$version/docs/'
    | '/$libraryId/$version/docs/framework/'
    | '/$libraryId/$version/docs/framework/$framework/$'
    | '/$libraryId/$version/docs/framework/$framework/{$}.md'
    | '/$libraryId/$version/docs/framework/$framework/'
    | '/$libraryId/$version/docs/framework/$framework/examples/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryIdRouteRoute: typeof LibraryIdRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AccountRoute: typeof AccountRouteWithChildren
  AdsRoute: typeof AdsRoute
  BlogRoute: typeof BlogRouteWithChildren
  BrandGuideRoute: typeof BrandGuideRoute
  BuilderRoute: typeof BuilderRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  EthosRoute: typeof EthosRoute
  ExploreRoute: typeof ExploreRoute
  FeedbackLeaderboardRoute: typeof FeedbackLeaderboardRoute
  LearnRoute: typeof LearnRoute
  LibrariesRoute: typeof LibrariesRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  MaintainersRoute: typeof MaintainersRoute
  MerchRoute: typeof MerchRoute
  PaidSupportRoute: typeof PaidSupportRoute
  PartnersRoute: typeof PartnersRoute
  PartnersEmbedRoute: typeof PartnersEmbedRoute
  PrivacyRoute: typeof PrivacyRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SponsorsEmbedRoute: typeof SponsorsEmbedRoute
  SupportRoute: typeof SupportRoute
  TenetsRoute: typeof TenetsRoute
  TermsRoute: typeof TermsRoute
  WorkshopsRoute: typeof WorkshopsRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  AuthPopupSuccessRoute: typeof AuthPopupSuccessRoute
  AuthSignoutRoute: typeof AuthSignoutRoute
  FeedIdRoute: typeof FeedIdRoute
  OauthAuthorizeRoute: typeof OauthAuthorizeRoute
  OauthRegisterRoute: typeof OauthRegisterRoute
  OauthTokenRoute: typeof OauthTokenRoute
  ShowcaseIdRoute: typeof ShowcaseIdRoute
  ShowcaseSubmitRoute: typeof ShowcaseSubmitRoute
  FeedIndexRoute: typeof FeedIndexRoute
  ShowcaseIndexRoute: typeof ShowcaseIndexRoute
  StatsIndexRoute: typeof StatsIndexRoute
  ApiAdminSyncRoute: typeof ApiAdminSyncRoute
  ApiBuilderCompileRoute: typeof ApiBuilderCompileRoute
  ApiBuilderCompileAttributedRoute: typeof ApiBuilderCompileAttributedRoute
  ApiBuilderDownloadRoute: typeof ApiBuilderDownloadRoute
  ApiBuilderFeatureArtifactsRoute: typeof ApiBuilderFeatureArtifactsRoute
  ApiBuilderFeaturesRoute: typeof ApiBuilderFeaturesRoute
  ApiBuilderLoadRemoteAddonRoute: typeof ApiBuilderLoadRemoteAddonRoute
  ApiBuilderLoadRemoteTemplateRoute: typeof ApiBuilderLoadRemoteTemplateRoute
  ApiBuilderLoadTemplateRoute: typeof ApiBuilderLoadTemplateRoute
  ApiBuilderSuggestRoute: typeof ApiBuilderSuggestRoute
  ApiBuilderValidateRoute: typeof ApiBuilderValidateRoute
  ApiDataLibrariesRoute: typeof ApiDataLibrariesRoute
  ApiDataPartnersRoute: typeof ApiDataPartnersRoute
  ApiDiscordInteractionsRoute: typeof ApiDiscordInteractionsRoute
  ApiExampleDeployRoute: typeof ApiExampleDeployRoute
  ApiGithubWebhookRoute: typeof ApiGithubWebhookRoute
  ApiMcpSplatRoute: typeof ApiMcpSplatRoute
  AuthProviderStartRoute: typeof AuthProviderStartRoute
  ShowcaseEditIdRoute: typeof ShowcaseEditIdRoute
  StatsNpmPackagesRoute: typeof StatsNpmPackagesRoute
  ApiMcpIndexRoute: typeof ApiMcpIndexRoute
  StatsNpmIndexRoute: typeof StatsNpmIndexRoute
  ApiAuthCallbackProviderRoute: typeof ApiAuthCallbackProviderRoute
  ApiBuilderDeployCheckNameRoute: typeof ApiBuilderDeployCheckNameRoute
  ApiBuilderDeployGithubRoute: typeof ApiBuilderDeployGithubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshops': {
      id: '/workshops'
      path: '/workshops'
      fullPath: '/workshops'
      preLoaderRoute: typeof WorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenets': {
      id: '/tenets'
      path: '/tenets'
      fullPath: '/tenets'
      preLoaderRoute: typeof TenetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors-embed': {
      id: '/sponsors-embed'
      path: '/sponsors-embed'
      fullPath: '/sponsors-embed'
      preLoaderRoute: typeof SponsorsEmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners-embed': {
      id: '/partners-embed'
      path: '/partners-embed'
      fullPath: '/partners-embed'
      preLoaderRoute: typeof PartnersEmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paid-support': {
      id: '/paid-support'
      path: '/paid-support'
      fullPath: '/paid-support'
      preLoaderRoute: typeof PaidSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch': {
      id: '/merch'
      path: '/merch'
      fullPath: '/merch'
      preLoaderRoute: typeof MerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintainers': {
      id: '/maintainers'
      path: '/maintainers'
      fullPath: '/maintainers'
      preLoaderRoute: typeof MaintainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries': {
      id: '/libraries'
      path: '/libraries'
      fullPath: '/libraries'
      preLoaderRoute: typeof LibrariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback-leaderboard': {
      id: '/feedback-leaderboard'
      path: '/feedback-leaderboard'
      fullPath: '/feedback-leaderboard'
      preLoaderRoute: typeof FeedbackLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ethos': {
      id: '/ethos'
      path: '/ethos'
      fullPath: '/ethos'
      preLoaderRoute: typeof EthosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-guide': {
      id: '/brand-guide'
      path: '/brand-guide'
      fullPath: '/brand-guide'
      preLoaderRoute: typeof BrandGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$libraryId': {
      id: '/$libraryId'
      path: '/$libraryId'
      fullPath: '/$libraryId'
      preLoaderRoute: typeof LibraryIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/': {
      id: '/stats/'
      path: '/stats'
      fullPath: '/stats/'
      preLoaderRoute: typeof StatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/': {
      id: '/showcase/'
      path: '/showcase'
      fullPath: '/showcase/'
      preLoaderRoute: typeof ShowcaseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/': {
      id: '/feed/'
      path: '/feed'
      fullPath: '/feed/'
      preLoaderRoute: typeof FeedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/': {
      id: '/builder/'
      path: '/'
      fullPath: '/builder/'
      preLoaderRoute: typeof BuilderIndexRouteImport
      parentRoute: typeof BuilderRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/$libraryId/': {
      id: '/$libraryId/'
      path: '/'
      fullPath: '/$libraryId/'
      preLoaderRoute: typeof LibraryIdIndexRouteImport
      parentRoute: typeof LibraryIdRouteRoute
    }
    '/showcase/submit': {
      id: '/showcase/submit'
      path: '/showcase/submit'
      fullPath: '/showcase/submit'
      preLoaderRoute: typeof ShowcaseSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/$id': {
      id: '/showcase/$id'
      path: '/showcase/$id'
      fullPath: '/showcase/$id'
      preLoaderRoute: typeof ShowcaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/token': {
      id: '/oauth/token'
      path: '/oauth/token'
      fullPath: '/oauth/token'
      preLoaderRoute: typeof OauthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/register': {
      id: '/oauth/register'
      path: '/oauth/register'
      fullPath: '/oauth/register'
      preLoaderRoute: typeof OauthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/authorize': {
      id: '/oauth/authorize'
      path: '/oauth/authorize'
      fullPath: '/oauth/authorize'
      preLoaderRoute: typeof OauthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/$id': {
      id: '/feed/$id'
      path: '/feed/$id'
      fullPath: '/feed/$id'
      preLoaderRoute: typeof FeedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/docs': {
      id: '/builder/docs'
      path: '/docs'
      fullPath: '/builder/docs'
      preLoaderRoute: typeof BuilderDocsRouteImport
      parentRoute: typeof BuilderRoute
    }
    '/blog/$': {
      id: '/blog/$'
      path: '/$'
      fullPath: '/blog/$'
      preLoaderRoute: typeof BlogSplatRouteImport
      parentRoute: typeof BlogRoute
    }
    '/auth/signout': {
      id: '/auth/signout'
      path: '/auth/signout'
      fullPath: '/auth/signout'
      preLoaderRoute: typeof AuthSignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/popup-success': {
      id: '/auth/popup-success'
      path: '/auth/popup-success'
      fullPath: '/auth/popup-success'
      preLoaderRoute: typeof AuthPopupSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/npm-stats': {
      id: '/admin/npm-stats'
      path: '/npm-stats'
      fullPath: '/admin/npm-stats'
      preLoaderRoute: typeof AdminNpmStatsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/logins': {
      id: '/admin/logins'
      path: '/logins'
      fullPath: '/admin/logins'
      preLoaderRoute: typeof AdminLoginsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/github-stats': {
      id: '/admin/github-stats'
      path: '/github-stats'
      fullPath: '/admin/github-stats'
      preLoaderRoute: typeof AdminGithubStatsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/submissions': {
      id: '/account/submissions'
      path: '/submissions'
      fullPath: '/account/submissions'
      preLoaderRoute: typeof AccountSubmissionsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/notes': {
      id: '/account/notes'
      path: '/notes'
      fullPath: '/account/notes'
      preLoaderRoute: typeof AccountNotesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/integrations': {
      id: '/account/integrations'
      path: '/integrations'
      fullPath: '/account/integrations'
      preLoaderRoute: typeof AccountIntegrationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/feedback': {
      id: '/account/feedback'
      path: '/feedback'
      fullPath: '/account/feedback'
      preLoaderRoute: typeof AccountFeedbackRouteImport
      parentRoute: typeof AccountRoute
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$libraryId/$version': {
      id: '/$libraryId/$version'
      path: '/$version'
      fullPath: '/$libraryId/$version'
      preLoaderRoute: typeof LibraryIdVersionRouteImport
      parentRoute: typeof LibraryIdRouteRoute
    }
    '/stats/npm/': {
      id: '/stats/npm/'
      path: '/stats/npm'
      fullPath: '/stats/npm/'
      preLoaderRoute: typeof StatsNpmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/': {
      id: '/api/mcp/'
      path: '/api/mcp'
      fullPath: '/api/mcp/'
      preLoaderRoute: typeof ApiMcpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/showcases/': {
      id: '/admin/showcases/'
      path: '/showcases'
      fullPath: '/admin/showcases/'
      preLoaderRoute: typeof AdminShowcasesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/roles/': {
      id: '/admin/roles/'
      path: '/roles'
      fullPath: '/admin/roles/'
      preLoaderRoute: typeof AdminRolesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notes/': {
      id: '/admin/notes/'
      path: '/notes'
      fullPath: '/admin/notes/'
      preLoaderRoute: typeof AdminNotesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/feedback/': {
      id: '/admin/feedback/'
      path: '/feedback'
      fullPath: '/admin/feedback/'
      preLoaderRoute: typeof AdminFeedbackIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/feed/': {
      id: '/admin/feed/'
      path: '/feed'
      fullPath: '/admin/feed/'
      preLoaderRoute: typeof AdminFeedIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/banners/': {
      id: '/admin/banners/'
      path: '/banners'
      fullPath: '/admin/banners/'
      preLoaderRoute: typeof AdminBannersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$libraryId/$version/': {
      id: '/$libraryId/$version/'
      path: '/'
      fullPath: '/$libraryId/$version/'
      preLoaderRoute: typeof LibraryIdVersionIndexRouteImport
      parentRoute: typeof LibraryIdVersionRoute
    }
    '/stats/npm/$packages': {
      id: '/stats/npm/$packages'
      path: '/stats/npm/$packages'
      fullPath: '/stats/npm/$packages'
      preLoaderRoute: typeof StatsNpmPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/edit/$id': {
      id: '/showcase/edit/$id'
      path: '/showcase/edit/$id'
      fullPath: '/showcase/edit/$id'
      preLoaderRoute: typeof ShowcaseEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$provider/start': {
      id: '/auth/$provider/start'
      path: '/auth/$provider/start'
      fullPath: '/auth/$provider/start'
      preLoaderRoute: typeof AuthProviderStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/$': {
      id: '/api/mcp/$'
      path: '/api/mcp/$'
      fullPath: '/api/mcp/$'
      preLoaderRoute: typeof ApiMcpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/webhook': {
      id: '/api/github/webhook'
      path: '/api/github/webhook'
      fullPath: '/api/github/webhook'
      preLoaderRoute: typeof ApiGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/example/deploy': {
      id: '/api/example/deploy'
      path: '/api/example/deploy'
      fullPath: '/api/example/deploy'
      preLoaderRoute: typeof ApiExampleDeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discord/interactions': {
      id: '/api/discord/interactions'
      path: '/api/discord/interactions'
      fullPath: '/api/discord/interactions'
      preLoaderRoute: typeof ApiDiscordInteractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data/partners': {
      id: '/api/data/partners'
      path: '/api/data/partners'
      fullPath: '/api/data/partners'
      preLoaderRoute: typeof ApiDataPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data/libraries': {
      id: '/api/data/libraries'
      path: '/api/data/libraries'
      fullPath: '/api/data/libraries'
      preLoaderRoute: typeof ApiDataLibrariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builder/validate': {
      id: '/api/builder/validate'
      path: '/api/builder/validate'
      fullPath: '/api/builder/validate'
      preLoaderRoute: typeof ApiBuilderValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builder/suggest': {
      id: '/api/builder/suggest'
      path: '/api/builder/suggest'
      fullPath: '/api/builder/suggest'
      preLoaderRoute: typeof ApiBuilderSuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builder/load-template': {
      id: '/api/builder/load-template'
      path: '/api/builder/load-template'
      fullPath: '/api/builder/load-template'
      preLoaderRoute: typeof ApiBuilderLoadTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builder/load-remote-template': {
      id: '/api/builder/load-remote-template'
      path: '/api/builder/load-remote-template'
      fullPath: '/api/builder/load-remote-template'
      preLoaderRoute: typeof ApiBuilderLoadRemoteTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builder/load-remote-addon': {
      id: '/api/builder/load-remote-addon'
      path: '/api/builder/load-remote-addon'
      fullPath: '/api/builder/load-remote-addon'
      preLoaderRoute: typeof ApiBuilderLoadRemoteAddonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builder/features': {
      id: '/api/builder/features'
      path: '/api/builder/features'
      fullPath: '/api/builder/features'
      preLoaderRoute: typeof ApiBuilderFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builder/feature-artifacts': {
      id: '/api/builder/feature-artifacts'
      path: '/api/builder/feature-artifacts'
      fullPath: '/api/builder/feature-artifacts'
      preLoaderRoute: typeof ApiBuilderFeatureArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builder/download': {
      id: '/api/builder/download'
      path: '/api/builder/download'
      fullPath: '/api/builder/download'
      preLoaderRoute: typeof ApiBuilderDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builder/compile-attributed': {
      id: '/api/builder/compile-attributed'
      path: '/api/builder/compile-attributed'
      fullPath: '/api/builder/compile-attributed'
      preLoaderRoute: typeof ApiBuilderCompileAttributedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builder/compile': {
      id: '/api/builder/compile'
      path: '/api/builder/compile'
      fullPath: '/api/builder/compile'
      preLoaderRoute: typeof ApiBuilderCompileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/sync': {
      id: '/api/admin/sync'
      path: '/api/admin/sync'
      fullPath: '/api/admin/sync'
      preLoaderRoute: typeof ApiAdminSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/showcases_/$id': {
      id: '/admin/showcases_/$id'
      path: '/showcases/$id'
      fullPath: '/admin/showcases/$id'
      preLoaderRoute: typeof AdminShowcasesIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/roles/$roleId': {
      id: '/admin/roles/$roleId'
      path: '/roles/$roleId'
      fullPath: '/admin/roles/$roleId'
      preLoaderRoute: typeof AdminRolesRoleIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/feedback_/$id': {
      id: '/admin/feedback_/$id'
      path: '/feedback/$id'
      fullPath: '/admin/feedback/$id'
      preLoaderRoute: typeof AdminFeedbackIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/feed/$id': {
      id: '/admin/feed/$id'
      path: '/feed/$id'
      fullPath: '/admin/feed/$id'
      preLoaderRoute: typeof AdminFeedIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/banners/$id': {
      id: '/admin/banners/$id'
      path: '/banners/$id'
      fullPath: '/admin/banners/$id'
      preLoaderRoute: typeof AdminBannersIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$libraryId/$version/docs': {
      id: '/$libraryId/$version/docs'
      path: '/docs'
      fullPath: '/$libraryId/$version/docs'
      preLoaderRoute: typeof LibraryIdVersionDocsRouteImport
      parentRoute: typeof LibraryIdVersionRoute
    }
    '/$libraryId/$version/docs/': {
      id: '/$libraryId/$version/docs/'
      path: '/'
      fullPath: '/$libraryId/$version/docs/'
      preLoaderRoute: typeof LibraryIdVersionDocsIndexRouteImport
      parentRoute: typeof LibraryIdVersionDocsRoute
    }
    '/api/builder/deploy/github': {
      id: '/api/builder/deploy/github'
      path: '/api/builder/deploy/github'
      fullPath: '/api/builder/deploy/github'
      preLoaderRoute: typeof ApiBuilderDeployGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builder/deploy/check-name': {
      id: '/api/builder/deploy/check-name'
      path: '/api/builder/deploy/check-name'
      fullPath: '/api/builder/deploy/check-name'
      preLoaderRoute: typeof ApiBuilderDeployCheckNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback/$provider': {
      id: '/api/auth/callback/$provider'
      path: '/api/auth/callback/$provider'
      fullPath: '/api/auth/callback/$provider'
      preLoaderRoute: typeof ApiAuthCallbackProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$libraryId/$version/docs/{$}.md': {
      id: '/$libraryId/$version/docs/{$}.md'
      path: '/{$}.md'
      fullPath: '/$libraryId/$version/docs/{$}.md'
      preLoaderRoute: typeof LibraryIdVersionDocsChar123Char125DotmdRouteImport
      parentRoute: typeof LibraryIdVersionDocsRoute
    }
    '/$libraryId/$version/docs/npm-stats': {
      id: '/$libraryId/$version/docs/npm-stats'
      path: '/npm-stats'
      fullPath: '/$libraryId/$version/docs/npm-stats'
      preLoaderRoute: typeof LibraryIdVersionDocsNpmStatsRouteImport
      parentRoute: typeof LibraryIdVersionDocsRoute
    }
    '/$libraryId/$version/docs/contributors': {
      id: '/$libraryId/$version/docs/contributors'
      path: '/contributors'
      fullPath: '/$libraryId/$version/docs/contributors'
      preLoaderRoute: typeof LibraryIdVersionDocsContributorsRouteImport
      parentRoute: typeof LibraryIdVersionDocsRoute
    }
    '/$libraryId/$version/docs/community-resources': {
      id: '/$libraryId/$version/docs/community-resources'
      path: '/community-resources'
      fullPath: '/$libraryId/$version/docs/community-resources'
      preLoaderRoute: typeof LibraryIdVersionDocsCommunityResourcesRouteImport
      parentRoute: typeof LibraryIdVersionDocsRoute
    }
    '/$libraryId/$version/docs/$': {
      id: '/$libraryId/$version/docs/$'
      path: '/$'
      fullPath: '/$libraryId/$version/docs/$'
      preLoaderRoute: typeof LibraryIdVersionDocsSplatRouteImport
      parentRoute: typeof LibraryIdVersionDocsRoute
    }
    '/$libraryId/$version/docs/framework/': {
      id: '/$libraryId/$version/docs/framework/'
      path: '/framework'
      fullPath: '/$libraryId/$version/docs/framework/'
      preLoaderRoute: typeof LibraryIdVersionDocsFrameworkIndexRouteImport
      parentRoute: typeof LibraryIdVersionDocsRoute
    }
    '/$libraryId/$version/docs/framework/$framework/': {
      id: '/$libraryId/$version/docs/framework/$framework/'
      path: '/framework/$framework'
      fullPath: '/$libraryId/$version/docs/framework/$framework/'
      preLoaderRoute: typeof LibraryIdVersionDocsFrameworkFrameworkIndexRouteImport
      parentRoute: typeof LibraryIdVersionDocsRoute
    }
    '/$libraryId/$version/docs/framework/$framework/{$}.md': {
      id: '/$libraryId/$version/docs/framework/$framework/{$}.md'
      path: '/framework/$framework/{$}.md'
      fullPath: '/$libraryId/$version/docs/framework/$framework/{$}.md'
      preLoaderRoute: typeof LibraryIdVersionDocsFrameworkFrameworkChar123Char125DotmdRouteImport
      parentRoute: typeof LibraryIdVersionDocsRoute
    }
    '/$libraryId/$version/docs/framework/$framework/$': {
      id: '/$libraryId/$version/docs/framework/$framework/$'
      path: '/framework/$framework/$'
      fullPath: '/$libraryId/$version/docs/framework/$framework/$'
      preLoaderRoute: typeof LibraryIdVersionDocsFrameworkFrameworkSplatRouteImport
      parentRoute: typeof LibraryIdVersionDocsRoute
    }
    '/$libraryId/$version/docs/framework/$framework/examples/$': {
      id: '/$libraryId/$version/docs/framework/$framework/examples/$'
      path: '/framework/$framework/examples/$'
      fullPath: '/$libraryId/$version/docs/framework/$framework/examples/$'
      preLoaderRoute: typeof LibraryIdVersionDocsFrameworkFrameworkExamplesSplatRouteImport
      parentRoute: typeof LibraryIdVersionDocsRoute
    }
  }
}

interface LibraryIdVersionDocsRouteChildren {
  LibraryIdVersionDocsSplatRoute: typeof LibraryIdVersionDocsSplatRoute
  LibraryIdVersionDocsCommunityResourcesRoute: typeof LibraryIdVersionDocsCommunityResourcesRoute
  LibraryIdVersionDocsContributorsRoute: typeof LibraryIdVersionDocsContributorsRoute
  LibraryIdVersionDocsNpmStatsRoute: typeof LibraryIdVersionDocsNpmStatsRoute
  LibraryIdVersionDocsChar123Char125DotmdRoute: typeof LibraryIdVersionDocsChar123Char125DotmdRoute
  LibraryIdVersionDocsIndexRoute: typeof LibraryIdVersionDocsIndexRoute
  LibraryIdVersionDocsFrameworkIndexRoute: typeof LibraryIdVersionDocsFrameworkIndexRoute
  LibraryIdVersionDocsFrameworkFrameworkSplatRoute: typeof LibraryIdVersionDocsFrameworkFrameworkSplatRoute
  LibraryIdVersionDocsFrameworkFrameworkChar123Char125DotmdRoute: typeof LibraryIdVersionDocsFrameworkFrameworkChar123Char125DotmdRoute
  LibraryIdVersionDocsFrameworkFrameworkIndexRoute: typeof LibraryIdVersionDocsFrameworkFrameworkIndexRoute
  LibraryIdVersionDocsFrameworkFrameworkExamplesSplatRoute: typeof LibraryIdVersionDocsFrameworkFrameworkExamplesSplatRoute
}

const LibraryIdVersionDocsRouteChildren: LibraryIdVersionDocsRouteChildren = {
  LibraryIdVersionDocsSplatRoute: LibraryIdVersionDocsSplatRoute,
  LibraryIdVersionDocsCommunityResourcesRoute:
    LibraryIdVersionDocsCommunityResourcesRoute,
  LibraryIdVersionDocsContributorsRoute: LibraryIdVersionDocsContributorsRoute,
  LibraryIdVersionDocsNpmStatsRoute: LibraryIdVersionDocsNpmStatsRoute,
  LibraryIdVersionDocsChar123Char125DotmdRoute:
    LibraryIdVersionDocsChar123Char125DotmdRoute,
  LibraryIdVersionDocsIndexRoute: LibraryIdVersionDocsIndexRoute,
  LibraryIdVersionDocsFrameworkIndexRoute:
    LibraryIdVersionDocsFrameworkIndexRoute,
  LibraryIdVersionDocsFrameworkFrameworkSplatRoute:
    LibraryIdVersionDocsFrameworkFrameworkSplatRoute,
  LibraryIdVersionDocsFrameworkFrameworkChar123Char125DotmdRoute:
    LibraryIdVersionDocsFrameworkFrameworkChar123Char125DotmdRoute,
  LibraryIdVersionDocsFrameworkFrameworkIndexRoute:
    LibraryIdVersionDocsFrameworkFrameworkIndexRoute,
  LibraryIdVersionDocsFrameworkFrameworkExamplesSplatRoute:
    LibraryIdVersionDocsFrameworkFrameworkExamplesSplatRoute,
}

const LibraryIdVersionDocsRouteWithChildren =
  LibraryIdVersionDocsRoute._addFileChildren(LibraryIdVersionDocsRouteChildren)

interface LibraryIdVersionRouteChildren {
  LibraryIdVersionDocsRoute: typeof LibraryIdVersionDocsRouteWithChildren
  LibraryIdVersionIndexRoute: typeof LibraryIdVersionIndexRoute
}

const LibraryIdVersionRouteChildren: LibraryIdVersionRouteChildren = {
  LibraryIdVersionDocsRoute: LibraryIdVersionDocsRouteWithChildren,
  LibraryIdVersionIndexRoute: LibraryIdVersionIndexRoute,
}

const LibraryIdVersionRouteWithChildren =
  LibraryIdVersionRoute._addFileChildren(LibraryIdVersionRouteChildren)

interface LibraryIdRouteRouteChildren {
  LibraryIdVersionRoute: typeof LibraryIdVersionRouteWithChildren
  LibraryIdIndexRoute: typeof LibraryIdIndexRoute
}

const LibraryIdRouteRouteChildren: LibraryIdRouteRouteChildren = {
  LibraryIdVersionRoute: LibraryIdVersionRouteWithChildren,
  LibraryIdIndexRoute: LibraryIdIndexRoute,
}

const LibraryIdRouteRouteWithChildren = LibraryIdRouteRoute._addFileChildren(
  LibraryIdRouteRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminGithubStatsRoute: typeof AdminGithubStatsRoute
  AdminLoginsRoute: typeof AdminLoginsRoute
  AdminNpmStatsRoute: typeof AdminNpmStatsRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBannersIdRoute: typeof AdminBannersIdRoute
  AdminFeedIdRoute: typeof AdminFeedIdRoute
  AdminFeedbackIdRoute: typeof AdminFeedbackIdRoute
  AdminRolesRoleIdRoute: typeof AdminRolesRoleIdRoute
  AdminShowcasesIdRoute: typeof AdminShowcasesIdRoute
  AdminBannersIndexRoute: typeof AdminBannersIndexRoute
  AdminFeedIndexRoute: typeof AdminFeedIndexRoute
  AdminFeedbackIndexRoute: typeof AdminFeedbackIndexRoute
  AdminNotesIndexRoute: typeof AdminNotesIndexRoute
  AdminRolesIndexRoute: typeof AdminRolesIndexRoute
  AdminShowcasesIndexRoute: typeof AdminShowcasesIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminGithubStatsRoute: AdminGithubStatsRoute,
  AdminLoginsRoute: AdminLoginsRoute,
  AdminNpmStatsRoute: AdminNpmStatsRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminBannersIdRoute: AdminBannersIdRoute,
  AdminFeedIdRoute: AdminFeedIdRoute,
  AdminFeedbackIdRoute: AdminFeedbackIdRoute,
  AdminRolesRoleIdRoute: AdminRolesRoleIdRoute,
  AdminShowcasesIdRoute: AdminShowcasesIdRoute,
  AdminBannersIndexRoute: AdminBannersIndexRoute,
  AdminFeedIndexRoute: AdminFeedIndexRoute,
  AdminFeedbackIndexRoute: AdminFeedbackIndexRoute,
  AdminNotesIndexRoute: AdminNotesIndexRoute,
  AdminRolesIndexRoute: AdminRolesIndexRoute,
  AdminShowcasesIndexRoute: AdminShowcasesIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AccountRouteChildren {
  AccountFeedbackRoute: typeof AccountFeedbackRoute
  AccountIntegrationsRoute: typeof AccountIntegrationsRoute
  AccountNotesRoute: typeof AccountNotesRoute
  AccountSubmissionsRoute: typeof AccountSubmissionsRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountFeedbackRoute: AccountFeedbackRoute,
  AccountIntegrationsRoute: AccountIntegrationsRoute,
  AccountNotesRoute: AccountNotesRoute,
  AccountSubmissionsRoute: AccountSubmissionsRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface BlogRouteChildren {
  BlogSplatRoute: typeof BlogSplatRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSplatRoute: BlogSplatRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface BuilderRouteChildren {
  BuilderDocsRoute: typeof BuilderDocsRoute
  BuilderIndexRoute: typeof BuilderIndexRoute
}

const BuilderRouteChildren: BuilderRouteChildren = {
  BuilderDocsRoute: BuilderDocsRoute,
  BuilderIndexRoute: BuilderIndexRoute,
}

const BuilderRouteWithChildren =
  BuilderRoute._addFileChildren(BuilderRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryIdRouteRoute: LibraryIdRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AccountRoute: AccountRouteWithChildren,
  AdsRoute: AdsRoute,
  BlogRoute: BlogRouteWithChildren,
  BrandGuideRoute: BrandGuideRoute,
  BuilderRoute: BuilderRouteWithChildren,
  DashboardRoute: DashboardRoute,
  EthosRoute: EthosRoute,
  ExploreRoute: ExploreRoute,
  FeedbackLeaderboardRoute: FeedbackLeaderboardRoute,
  LearnRoute: LearnRoute,
  LibrariesRoute: LibrariesRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  MaintainersRoute: MaintainersRoute,
  MerchRoute: MerchRoute,
  PaidSupportRoute: PaidSupportRoute,
  PartnersRoute: PartnersRoute,
  PartnersEmbedRoute: PartnersEmbedRoute,
  PrivacyRoute: PrivacyRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SponsorsEmbedRoute: SponsorsEmbedRoute,
  SupportRoute: SupportRoute,
  TenetsRoute: TenetsRoute,
  TermsRoute: TermsRoute,
  WorkshopsRoute: WorkshopsRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
  AuthPopupSuccessRoute: AuthPopupSuccessRoute,
  AuthSignoutRoute: AuthSignoutRoute,
  FeedIdRoute: FeedIdRoute,
  OauthAuthorizeRoute: OauthAuthorizeRoute,
  OauthRegisterRoute: OauthRegisterRoute,
  OauthTokenRoute: OauthTokenRoute,
  ShowcaseIdRoute: ShowcaseIdRoute,
  ShowcaseSubmitRoute: ShowcaseSubmitRoute,
  FeedIndexRoute: FeedIndexRoute,
  ShowcaseIndexRoute: ShowcaseIndexRoute,
  StatsIndexRoute: StatsIndexRoute,
  ApiAdminSyncRoute: ApiAdminSyncRoute,
  ApiBuilderCompileRoute: ApiBuilderCompileRoute,
  ApiBuilderCompileAttributedRoute: ApiBuilderCompileAttributedRoute,
  ApiBuilderDownloadRoute: ApiBuilderDownloadRoute,
  ApiBuilderFeatureArtifactsRoute: ApiBuilderFeatureArtifactsRoute,
  ApiBuilderFeaturesRoute: ApiBuilderFeaturesRoute,
  ApiBuilderLoadRemoteAddonRoute: ApiBuilderLoadRemoteAddonRoute,
  ApiBuilderLoadRemoteTemplateRoute: ApiBuilderLoadRemoteTemplateRoute,
  ApiBuilderLoadTemplateRoute: ApiBuilderLoadTemplateRoute,
  ApiBuilderSuggestRoute: ApiBuilderSuggestRoute,
  ApiBuilderValidateRoute: ApiBuilderValidateRoute,
  ApiDataLibrariesRoute: ApiDataLibrariesRoute,
  ApiDataPartnersRoute: ApiDataPartnersRoute,
  ApiDiscordInteractionsRoute: ApiDiscordInteractionsRoute,
  ApiExampleDeployRoute: ApiExampleDeployRoute,
  ApiGithubWebhookRoute: ApiGithubWebhookRoute,
  ApiMcpSplatRoute: ApiMcpSplatRoute,
  AuthProviderStartRoute: AuthProviderStartRoute,
  ShowcaseEditIdRoute: ShowcaseEditIdRoute,
  StatsNpmPackagesRoute: StatsNpmPackagesRoute,
  ApiMcpIndexRoute: ApiMcpIndexRoute,
  StatsNpmIndexRoute: StatsNpmIndexRoute,
  ApiAuthCallbackProviderRoute: ApiAuthCallbackProviderRoute,
  ApiBuilderDeployCheckNameRoute: ApiBuilderDeployCheckNameRoute,
  ApiBuilderDeployGithubRoute: ApiBuilderDeployGithubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
