name: Broken link checker

on:
  schedule:
    - cron: '0 13 * * 1-5'
  workflow_dispatch:

jobs:
  broken-link-checker:
    name: Broken link checker
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - name: Install Packages
        run: pnpm install --frozen-lockfile
      - run: pnpm blc https://tanstack.com -ro --excludeExternalLinks