name: PR

on:
  pull_request:

permissions:
  contents: read

jobs:
  pr:
    name: PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Tools
        uses: tanstack/config/.github/setup@8f433551298bae362c0e7a356f38c7d240c05d47 # main
      - name: Run Build
        run: pnpm build
      - name: Run Tests
        run: pnpm test
