name: PR

on:
  pull_request:

permissions:
  contents: read

jobs:
  pr:
    name: PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Tools
        uses: tanstack/config/.github/setup@e4b48f16568324f76f467aa4c2aac2f05db632c3 # main
      - name: Run Build
        run: pnpm build
      - name: Run Tests
        run: pnpm test
